### ISSUE TITLE
Spoiler-gate Problem Sleuth content?

### ISSUE THREAD

**Issue by thecnoNSMB** [Bambosh/unofficial-homestuck-collection#109]
I was exploring the app in New Reader mode, and although the Homestuck spoilers seem very effectively hidden, I discovered a couple places where Problem Sleuth spoilers can be found in the extras. The ones I've found (I didn't want to look too hard since I haven't read PS yet) are:

- MSPA Newsposts 3 December 2008
- A bunch of the PS unlockable content/fan-requested commands
- Pretty much the entire Science FAQ

I was wondering if it'd be possible or worth it to spoiler-gate this stuff in similar fashion to the Homestuck extras.

**Comment by thecnoNSMB** [comment]
The Problem Sleuth Adventure Map probably counts too, now that I think about it.

**Comment by thecnoNSMB** [comment]
also Ryanquest includes a picture of a spoiler-gated newspost but I don't think that one actually contains any spoilers. Pointing it out just in case though.

**Comment by GiovanH** [comment]
This is a good idea; since PS use the same set of page numbers it should be fairly easy to handle these spoilers too.

**Comment by GiovanH** [comment]
Using http://web.archive.org/web/20081205001303/http://www.mspaintadventures.com:80/unlock.html as a rough outline for what unlock pages were released at what time.

**Comment by thecnoNSMB** [comment]
> Using http://web.archive.org/web/20081205001303/http://www.mspaintadventures.com:80/unlock.html as a rough outline for what unlock pages were released at what time.

The unlock pages appear to have been listed in the News section as they were added.
