### ISSUE TITLE
Assets behind symlinks are inaccessible

### ISSUE THREAD

**Issue by VikoRifeo** [Bambosh/unofficial-homestuck-collection#115]
This is a bit niche &ndash; just a bit &ndash; but if the assets are behind symlinks, the asset pack is detected as intact, but none of the contents load.

**Comment by GiovanH** [comment]
On a unix-like OS, I assume?

**Comment by VikoRifeo** [comment]
Yes.

**Comment by GiovanH** [comment]
This is going to be a limitation of how Electron handles the filesystem, and there's not much we can do about it here. There may be os-specific workarounds to creating disconnected directory structures (see NTFS junctions, for example, which work fine.)
