### ISSUE TITLE
(Option) Notifications when new readers reach a new newspost

### ISSUE THREAD

**Issue by GiovanH** [Bambosh/unofficial-homestuck-collection#117]

**Comment by Niklink** [comment]
There are a lot of newsposts, like a lot a lot. ~400, although I think 100 of those were pre-Homestuck. Still though, if this were to be implemented, I think it should be disabled by default. It's too many notifications for too many things that aren't great context, like all the stuff about merch and con appearances.

**Comment by GiovanH** [comment]
Oops, looks like this issue is a duplicate of #65
