### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by Mistsofnowh3r3** [Bambosh/unofficial-homestuck-collection#12]
1. A way to hide the taskbar. For me having the taskbar is distracting. 
2. Full screen flashes. I'm not even going to pretend to have any idea if this is even feasible, but it's the biggest gripe I had with original Homestuck.

**Comment by Bambosh** [comment]
1. Hiding the application header probably isn't something that'll happen for a while, if at all.
2. Fullscreen flashes aren't really feasible, but you can still zoom in on them I guess?

**Comment by thecnoNSMB** [comment]
If you have a [Flash projector](https://www.adobe.com/support/flashplayer/debug_downloads.html), you can try playing the animations in it in full screen. Though note they might break, or show stuff outside the borders that's supposed to be hidden.
