### ISSUE TITLE
Lag in openbound segments

### ISSUE THREAD

**Issue by Mistsofnowh3r3** [Bambosh/unofficial-homestuck-collection#125]
This could be a issue with my setup but, the openbound sections (that being https://www.homestuck.com/story/5263 , https://www.homestuck.com/story/5308 , https://www.homestuck.com/story/5398). Have lag/stuttering issues when using the collection but when I open those sections on my browser and go to the actual homestuck pages I have no issues.

**Comment by GiovanH** [comment]
Haven't been able to reproduce this, will circle back around to it

**Comment by Mistsofnowh3r3** [comment]
Sorry, I should have been more specific. What I meant is that when walking in the Openbound segments the scrolling is a little choppier in the collection then it is in chrome. Though looking at it now I think that Openbound is just a kinda choppy either way.

**Comment by GiovanH** [comment]
Openbound runs at 30fps and is a lot choppier than people remember it being. I may have something in the works for that ;)

**Comment by Mistsofnowh3r3** [comment]
Well, feel free to close this issue then. Looking forward to whatever plan you have in the works.
