### ISSUE TITLE
Music suddenly not working

### ISSUE THREAD

**Issue by Deesoff** [Bambosh/unofficial-homestuck-collection#140]
After having used the collection for a while with no issue it now made it so when I go to listen to any music in it it shows this instead of the normal grey embed and the play button doesn't work.
![image](https://user-images.githubusercontent.com/39684566/120552378-66bb1b80-c3b4-11eb-9def-609b9f2e91c1.png)
Edit: As the other reply said it seems to have now fixed itself for some reason so I'm gonna close the issue.

**Comment by Niklink** [comment]
Same here. Seems like Bandcamp embeds are broken somehow?
