### ISSUE TITLE
The Search function is tuned for english only.

### ISSUE THREAD

**Issue by Zhurnev** [Bambosh/unofficial-homestuck-collection#150]
If the search data file is changed to non-english symbols, search doesn't work for said symbols.
<br>
![image](https://user-images.githubusercontent.com/85682618/121519230-2124d100-c9fa-11eb-8a45-8883691fa378.png)
![image](https://user-images.githubusercontent.com/85682618/121519268-300b8380-c9fa-11eb-9f67-57449578d9bb.png)
![image](https://user-images.githubusercontent.com/85682618/121519399-592c1400-c9fa-11eb-81aa-f37891e1885a.png)

**Comment by GiovanH** [comment]
Search data file will be replaced with some new implementation
