### ISSUE TITLE
Announcing updates through the browser

### ISSUE THREAD

**Issue by Proxiehunter** [Bambosh/unofficial-homestuck-collection#17]
The only reason I found out 1.1 existed is because I randomly decided to check Homestuck reddit. I've checked and the browser gives no indication there's been an update. If the next version can be coded to announce future updates that would be helpful to users who want to make sure they have the current version installed.

**Comment by Bambosh** [comment]
This was an intentional decision, with two main reasons behind it:
1. I want to keep internet connection to an absolute minimum. The Bandcamp embed is pretty much the only exception to this.
2. As an archival project, the idea of the archive telling people to update kinda rubs me the wrong way. It feels uncomfortable, like I'm intentionally making it inconvenient to continue using the thing that should be capable of lasting forever in isolation. I want updates to be purely optional, so that any one version of the program can pass as a "complete and final" sort of thing.

**Comment by ReiDuran** [comment]
> 2. As an archival project, the idea of the archive telling people to update kinda rubs me the wrong way. It feels uncomfortable, like I'm intentionally making it inconvenient to continue using the thing that should be capable of lasting forever in isolation. I want updates to be purely optional, so that any one version of the program can pass as a "complete and final" sort of thing.

Maybe a good compromise would be to add a "check for updates" button to the system settings? That way you're not pushing updates in people's faces by connecting to the internet all the time, but people who want to quickly see if there's any fixes or updates can get to them from the Collection itself.

**Comment by GiovanH** [comment]
> As an archival project, the idea of the archive telling people to update kinda rubs me the wrong way.

I get what you're going for here, but I disagree. An archive update already means there *is* a significant reason to upgrade, or it wouldn't have been developed and released in the first place. 

I definitely think update notifications could be optional, set up in an unobtrusive way, and have an option to "skip this version" if requested.

I think "check for updates" is a good compromise, at least?

**Comment by Bambosh** [comment]
I'm definitely starting to flip on this. It shouldn't be too hard to work out something that doesn't get in the way of things.

**Comment by GiovanH** [comment]
Some backend thoughts on this:

- Have a json file on the GitHub.io page that lists each version release, the date it was released, and whether it required an asset pack update 
- Have a GitHub/changelog page where we’ll direct updating users. It should have links to update the relevant files and then a high-level version changelog under that 

Then automatically ping that json file when the app runs, prompt the user to update if there’s an update. Have an option to skip versions and store skipped versions in localstorage. Maybe note somewhere if there’s a connection issue and updates couldn’t be checked for. Have an option to disable all this.
