### ISSUE TITLE
various issues

### ISSUE THREAD

**Issue by jseakle** [Bambosh/unofficial-homestuck-collection#18]
I'm going to use this to catalogue problems I find as I read. they are mostly small, so it seems silly to make separate issues for each. let me know if there's a better way.

- ~~The link to formspring in the 2011-01-16 newspost just links to /formspring which defaults to the top of the andrewhussie formspring, even though it's specifically announcing the mspaintadventures one. This was very confusing for a while, it would be great if the two had separate jump bar URLs links from this point forward were corrected.~~ being handled in #34 

- It would be nice if your "reverse post order" selection were respected when switching back and forth between formsprings.

- The newspost interface is quite frustrating, because clicking away from it loses your place. I think it would be better if the years were just on separate pages (or even if all the posts were on one page, without the year collapsing) so that the browser's default page position behavior works with the back and forward buttons

- The mspaintadventures formspring question to which the answer begins "They look similar.." has been incorrectly replaced with "Jan 15, 2011 - Jan 24, 2011". The actual question text is 
```#question2172660818 Then how come Viriska's and Aradia's outfits look almost the same? and are ALL Trolls shown as bugs? Are Trolls eventually insects that walk like men?```

- It would be nice if closing a tab focused the previously-focused tab, rather than the one to the right. Or at least the one to the left by default, since that's where you'll have just come from if you just opened a link in a new tab.

- it would be nice to have an off-by-default option to put translated morse directly on those pages

larger feature requests, i can make these their own issues if you want:

- there are a number of dead external links from newsposts that are available via archive.org. it would be cool if the ones that are were replaced with such links, or if the archived content were added to the bundle.

- similarly, there are a bunch of linked images that are still live but not included in the bundle, such as http://www.alexandra-douglass.com/special/612_wallpaper.jpg. presumably all of these will go away at some point too, so it would be nice to include them.

- it would be nice if the music credit links on pages had play buttons that expanded them into bandcamp embeds

**Comment by GiovanH** [comment]
> similarly, there are a bunch of linked images that are still live but not included in the bundle, such as http://www.alexandra-douglass.com/special/612_wallpaper.jpg. presumably all of these will go away at some point too, so it would be nice to include them.

> there are a number of dead external links from newsposts that are available via archive.org. it would be cool if the ones that are were replaced with such links, or if the archived content were added to the bundle.

It would be helpful if you could make a list of these cases and where they appear.

**Comment by GiovanH** [comment]
You can remove 

> The link to formspring in the 2011-01-16 newspost just links to /formspring which defaults to the top of the andrewhussie formspring, even though it's specifically announcing the mspaintadventures one. This was very confusing for a while, it would be great if the two had separate jump bar URLs links from this point forward were corrected.

from this issue (see #34)

**Comment by jseakle** [comment]
> It would be helpful if you could make a list of these cases and where they appear.

I will make sure to list them as I come across them from now on. Can't promise I'll find the time to go back and list the ones I've already passed, but I'll keep it in mind in case I do.

**Comment by GiovanH** [comment]
"They look similar.." is noted and will be patched in the next asset pack

**Comment by jseakle** [comment]
http://thingsnorthbought.tumblr.com/ (linked from 2012-08-20 tumblr post) is online but all the images are broken. they are available in the wayback machine though, making this a reasonable candidate for inclusion in a future version. http://thingshussiebought.tumblr.com/ currently has the images intact, but who knows how long that will last.
