### ISSUE TITLE
In-Homestuck music playlist

### ISSUE THREAD

**Issue by recordcrash** [Bambosh/unofficial-homestuck-collection#186]
It's a shame that the vast majority of the Homestuck soundtrack never got used. A good way to use it would be to play random appropriate songs as the player reads Homestuck, via an embedded player (using bandcamp? youtube?). This would need a new JSON file that linked specific tracks to specific spans of pages, and a whole new embedded player component.

Important: do not restart the track every page change, obviously, keep the component independent of navigation, easily closable, customization, etc.

**Comment by GiovanH** [comment]
We don't actually package the music with the assets, so this would be the bandcamp embed player on a widget on page.vue, combined with some sort of programmatic playlist logic
