### ISSUE TITLE
getExt() in MediaEmbed.vue breaks if parameter isn't a string

### ISSUE THREAD

**Issue by Bambosh** [Bambosh/unofficial-homestuck-collection#199]
![image](https://user-images.githubusercontent.com/28245739/132976703-662f39f0-9192-435b-8379-84a9652d23ec.png)
![image](https://user-images.githubusercontent.com/28245739/132976713-d6915e3e-891f-4bac-987c-181bc006ffb4.png)

**Comment by GiovanH** [comment]
The bug here seems to be that something is passing MediaEmbed an entirely blank url.
