### ISSUE TITLE
Files are corrupted

### ISSUE THREAD

**Issue by robbieradiant** [Bambosh/unofficial-homestuck-collection#215]
Some files in the asset pack are corrupted, making it so you can't read very far. I've tried the torrent and the mediafire, and they all have corrupted files. I've tried extracting with Windows, 7Zip, and WinRar. All of them still result in corrupted files. This makes the program absolutely useless.

**Comment by noirscape** [comment]
are you sure your hard drive isn't degrading in preformance?

the asset pack looks fine on my end.

**Comment by GiovanH** [comment]
Can't reproduce, closing stale issue
