### ISSUE TITLE
The images won't load on any of the acts, how do I fix this? 

### ISSUE THREAD

**Issue by ZillyhooMoment** [Bambosh/unofficial-homestuck-collection#217]
For some reason no images won't load on anything and it is only text.

**Comment by thecnoNSMB** [comment]
Did you download the asset pack correctly?

**Comment by ZillyhooMoment** [comment]
I'll try reinstalling the asset pack, thanks!

**Comment by GiovanH** [comment]
@ZillyhooMoment Were you able to resolve this issue?

**Comment by GiovanH** [comment]
Couldn't get followup info, closing
