### ISSUE TITLE
Descend & Make her pay wrong credits link

### ISSUE THREAD

**Issue by Niklink** [Bambosh/unofficial-homestuck-collection#246]
Both of these flashes have two links at the end screen that link to `/credits/artcredits` and `/credits/soundcredits`, but the latter is no longer a valid page so it just shows the `/credits` page instead of going to `/music/features`.

**Comment by GiovanH** [comment]
Curious. In-app, `/credits/soundcredits` does redirect to `/music/features`; possibly a quirk of flash redirection?

**Comment by GiovanH** [comment]
Resolved eef3891100edd9c37b857c794a68f89a151d9196
