### ISSUE TITLE
Userscripts

### ISSUE THREAD

**Issue by mendelsimon** [Bambosh/unofficial-homestuck-collection#250]
Is there any way to inject userscripts?
When I read Homestuck in Chrome, I used TamperMonkey to write small QoL scripts, such as making the leetspeak easier to read.
I don't need the full-blown mod capabilities; I just want to run small snippets of JS on each page. 
Is there currently any way to do this?
If not, I suppose this is a feature request.

**Comment by GiovanH** [comment]
This is a big part of the modding api, see https://github.com/Bambosh/unofficial-homestuck-collection/issues/43

Closing as a duplicate, but please feel free to make suggestions on the issue linked above!
