### ISSUE TITLE
Laggy flashes

### ISSUE THREAD

**Issue by Gastlu** [Bambosh/unofficial-homestuck-collection#258]
for some reason all the flashes are kind of laggy, even after deactivating high quality audio and enhanced effects. I opened a flash projector to see if it was my computer, but it ran normally.

**Comment by Bambosh** [comment]
Kinda tough to pin down, due to the inherent suckiness of flash as a platform. The forthcoming update bumps up the version of the internal flash plugin, so that should hopefully carry some performance optimizations.
