### ISSUE TITLE
Syncing progress in Homestuck between computers w/in New Reader Mode?

### ISSUE THREAD

**Issue by WilliamImm** [Bambosh/unofficial-homestuck-collection#27]
I'm interested in reading this project across multiple computers and would like to maintain progress between them as much as possible, however, the new reader mode currently doesn't allow me to update the position of where I am within the story, manually or via syncing.

Could a way to sync and/or manually adjust the Homestuck new reader current page be added in?

**Comment by Niklink** [comment]
A couple workarounds:

I'm pretty sure you can go to (in Windows) C:\Users\[username]\AppData\Roaming\unofficial-homestuck-collection and copy the file 'config.json' to the equivalent folder on the other computer. That OUGHT to transfer your settings, including your new reader mode progress and your save/load bookmarks, but it'll prompt you about not being able to find the asset pack and you'll have to re-set the asset pack directory every time. I don't really have another computer to test this solution though so idk if I'm overlooking something.

Or you can just memorize or write down your current page number, go to settings on the other computer, disable new reader mode (don't scroll through the settings with the new reader mode disabled, there are a few stray spoilers further down the page), and it'll let you input a page number to reactivate new reader mode with. All changes take effect instantly so you should be good to then jump to the page where you left off.

**Comment by GiovanH** [comment]
If you want a really snappy way to do this seamlessly between multiple windows machines, try this:

1. Move your latest `config.json` from `%appdata%/unofficial-homestuck-collection/config.json` to a shared network folder (Dropbox, Mega, pCloud, Onedrive (probably))
2. On each of your machines, make a *symbolic link* from the network location to `%appdata%/unofficial-homestuck-collection/config.json` 
(look at [Shell Link Ext[(https://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html) for this)
3. It Just Works

**Comment by WilliamImm** [comment]
This would work but I don't always use Windows on the machines I intend to read this on

**Comment by GiovanH** [comment]
(semi)-resolved with #48.
