### ISSUE TITLE
Formspring andrewhussie1818492115: pseudo-HTML tag is not escaped

### ISSUE THREAD

**Issue by m-jowa1863** [Bambosh/unofficial-homestuck-collection#271]
**Describe the bug**
```
<h2><a href="/formspring/andrewhussie1818492115">
There is an error on http://www.mspaintadventures.com/?s=6&amp;p=004942 (<black>The Tumor</black>).
</a></h2>
```

**Desktop (please complete the following information):**
 - Program version: v1.1.0
 - Asset Pack Version: v1
 - OS: Linux

**Additional context**
Ironic.

**Comment by GiovanH** [comment]
> Does html even support a <black> tag? Does any language, other than various slapdash custom scripts out there?
the answer is yes
