### ISSUE TITLE
Asset Pack v2 readme.txt still says it's v1

### ISSUE THREAD

**Issue by thecnoNSMB** [Bambosh/unofficial-homestuck-collection#275]
As in the title. That's it. There's no trick.

**Comment by Niklink** [comment]
You used the patch option, yeah? Not really a good way to delete unused files by doing so, but the asset pack version is tracked at archive\data\version.json

**Comment by GiovanH** [comment]
Haha, whoops!

Fixed the readme, so the asset pack will be correct in subsequent downloads, but I'm definitely not going to make people redownload the whole thing.

**Comment by wyattscarpenter** [comment]
I downloaded asset pack v2 from the mediafire link at https://bambosh.github.io/unofficial-homestuck-collection/#download today and it still says v2; not sure if you already knew this was the case—it hardly matters either way, of course.
