### ISSUE TITLE
Homestuck Collection will not open on Linux

### ISSUE THREAD

**Issue by XtremeMusic2** [Bambosh/unofficial-homestuck-collection#277]
**Describe the bug**
The tar.gz version on Linux does not open.

**To Reproduce**
1. Open a terminal emulator in the collection folder.
2. Type out ./unofficial-homestuck-collection

**Expected behavior**
The Unofficial Homestuck Collection opens as normal.

**Screenshots**
![2022-02-14_12-11](https://user-images.githubusercontent.com/61671837/153913800-cfb5aa75-8334-4873-a925-65b3027acabf.png)

**Desktop (please complete the following information):**
 - Program version: 2.0.4
 - Asset Pack Version: V2
 - OS: [e.g. iOS]: Pop!_OS Linux

**Comment by sassacre** [comment]
Hi. What version of Pop! OS are you using?
And does this happen with the AppImage version too?

**Comment by XtremeMusic2** [comment]
i'm on version 21.10 of pop! os, and the appimage version, when double clicked, doesnt do anything

**Comment by CaviaPorcellus** [comment]
The .tar.gz Linux version of 2.0.4 runs fine for me on Kubuntu 21.10 in its default not-run-as-root state.
