### ISSUE TITLE
Home page bug report link should let you create templated bug reports like this one

### ISSUE THREAD

**Issue by recordcrash** [Bambosh/unofficial-homestuck-collection#279]
**Describe the bug**
"Report a Bug" takes you to a bug report page with no template, but a template exists. It should be used.

**To Reproduce**
Go to https://bambosh.github.io/unofficial-homestuck-collection/index.html and click Report a Bug. It takes you to https://github.com/Bambosh/unofficial-homestuck-collection/issues/new?labels=bug, avoiding the templated bug report behavior.

**Expected behavior**
Should take to https://github.com/Bambosh/unofficial-homestuck-collection/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
Fat Husky is the best dog.

**Comment by GiovanH** [comment]
@Bambosh this is an issue with the github.io page not using the new templates, just update the link

**Comment by Bambosh** [comment]
Resolved
