### ISSUE TITLE
Lowest bookmark hidden.

### ISSUE THREAD

**Issue by Holmishire** [Bambosh/unofficial-homestuck-collection#288]
The bottom of the "Game Data" sidebar is not aligned with the bottom of the window. This leads to the bottom-most bookmark not being visible. (I can confirm it's there by dragging down the bookmark immediately above it to swap places.) If the address bar is enabled, one-and-a-half bookmarks are hidden instead.

![image](https://user-images.githubusercontent.com/99726608/154044520-25fb7d02-472f-46d8-87eb-a9e23b8a16b0.png)

Windows 11. App v2.04, Assets v2 (using patch method).

**Comment by Bambosh** [comment]
Resolved in upcoming patch
