### ISSUE TITLE
Homestuck page 4815, labeled "DOTA" in the title of the tab, loads to an empty screen.

### ISSUE THREAD

**Issue by gaffyishere** [Bambosh/unofficial-homestuck-collection#293]
Page 4815 seems to be broken in the latest release as of writing this. Unlike the prior pages, including ones that use Flash, this page loads to a completely blank page. Digging through the asset pack seems to show the relevant files are there, it just doesn't look like they're really doing anything there.

![image](https://user-images.githubusercontent.com/99774600/154177342-7baaaa79-d0b9-4c81-9555-ccbd367f3352.png)

Above is a (rather uneventful) screenshot of the broken page. While I've been using mods since I downloaded 2.0.4, testing this page without any, as well as disabling things like the new dark mode incase they were problematic, didn't resolve this.

**Comment by GiovanH** [comment]
This should be a full-screen flash page, so no content except for the flash file. But you're also missing the flash file.

Can you upload your log files?

**Comment by gaffyishere** [comment]
[main.log](https://github.com/Bambosh/unofficial-homestuck-collection/files/8076024/main.log)

[renderer.log](https://github.com/Bambosh/unofficial-homestuck-collection/files/8076021/renderer.log)

[renderer.old.log](https://github.com/Bambosh/unofficial-homestuck-collection/files/8076023/renderer.old.log)

Unless I ended up in the wrong directory, I should've gotten everything included right here.

**Comment by Tantusar** [comment]
I am also having this problem, which also extends to GAME OVER... But not to shes8ack?
[main.log](https://github.com/Bambosh/unofficial-homestuck-collection/files/8079964/main.log)
[renderer.log](https://github.com/Bambosh/unofficial-homestuck-collection/files/8079965/renderer.log)

This error comes up in the DevTools verbatim, before (but not exclusively) lines 7998, 7986, and 7983 (which is to say before any other log messages related to GAME OVER and DOTA) in the renderer log.
```
TypeError: Cannot read property 'includes' of undefined
    at app.81b0302c.js:1
    at Array.forEach (<anonymous>)
    at o.nextPagesArray (app.81b0302c.js:1)
    at an.get (chunk-vendors.11c00462.js:317)
    at an.evaluate (chunk-vendors.11c00462.js:317)
    at o.nextPagesArray (chunk-vendors.11c00462.js:317)
    at o.Qs (app.81b0302c.js:1)
    at o.e._render (chunk-vendors.11c00462.js:317)
    at o.n (chunk-vendors.11c00462.js:317)
    at an.get (chunk-vendors.11c00462.js:317)
    at new an (chunk-vendors.11c00462.js:317)
    at Lr (chunk-vendors.11c00462.js:317)
    at o.Cn.$mount (chunk-vendors.11c00462.js:317)
    at o.Cn.$mount (chunk-vendors.11c00462.js:317)
    at init (chunk-vendors.11c00462.js:317)
    at f (chunk-vendors.11c00462.js:317)```

**Comment by gaffyishere** [comment]
Minor update to this I'd like to add: I've got a friend who's still on a pre-2.0.4 version (I'll say the exact one once I get that info from them) and while I don't have any of their files or anything, they have said that apparently DOTA _does_ work in that build. Not 100% how useful this is, but it might be relavent to share.

**Comment by gaffyishere** [comment]
Update again: they're on 1.1.0, incase this tip on it working in a prior version is helpful for tracking down the issue.

**Comment by leo60228** [comment]
I have the exact same issue on latest `develop`.

**Comment by leo60228** [comment]
The issue is on Page.vue line 145 and only occurs with the password page retcon disabled.

**Comment by Tantusar** [comment]
> The issue is on Page.vue line 145 and only occurs with the password page retcon disabled.

Which, of course, if you're using new reader mode, (not a new reader, was trying to experience it as it happened) it is, because that retcon isn't enabled until /homestuck/7157. Can reproduce behaviour.

**Comment by GiovanH** [comment]
Fixed.
