### ISSUE TITLE
Mod list unreadable in Collide/PXS themes

### ISSUE THREAD

**Issue by Niklink** [Bambosh/unofficial-homestuck-collection#314]
On latest develop commit, but I'm pretty sure that doesn't matter. White text on light grey background is pretty hard to make out.

![image](https://user-images.githubusercontent.com/25875275/154783873-14fe2156-b764-4f95-bdf2-840eab713294.png)
![image](https://user-images.githubusercontent.com/25875275/154783884-921e760a-67e1-4f07-a4c0-e374dde46765.png)

**Comment by GiovanH** [comment]
Fixed e6c4e15c2b401f3f4a61cccea60072af7f138713
