### ISSUE TITLE
Enable controversial content for new readers

### ISSUE THREAD

**Issue by GiovanH** [Bambosh/unofficial-homestuck-collection#32]
Even in new reader mode, there should be an option to switch on "Controversial Content". New readers should have an option (in the options menu, not forced on them) to enable the controversial content that was present when that page was originally published, so people have the option to read the comic as it was originally intended. 

This would enable Bolin music, Caucasian, and the Tavros Banana, although it would *not* need to enable Skaianet Systems, as that was clearly a hidden easter egg and *not* part of the original presentation.

Obviously, this doesn't allow detailed content warnings like the current system does, so it's important that the message has a strong general warning.

**Comment by Bambosh** [comment]
Unlikely to change. Giving new readers choices about things they have no context for is gonna force them to ask questions about what they're enabling, and those questions lead directly to spoilers. These settings are best suited as a novelty for people who have already finished the comic and are curious about its removed content.

**Comment by GiovanH** [comment]
> Giving new readers choices about things they have no context for is gonna force them to ask questions about what they're enabling, and those questions lead directly to spoilers.

I don't think this is true, though. The relevant changes are "swapped music", "race mention" and "gore", which can definitely be described without spoiling any content, as I did just now. 

As I mentioned, this should definitely be behind content warnings -- possibly multiple layers -- but I definitely think that preserving the ability to read the material as it was originally presented is an important enough role for an archive that it's worth including.

**Comment by GiovanH** [comment]
I had a conversation on Twitter this morning that reminded me that a significant part of what made some of the "controversial" material controversial was the ongoing community discourse -- for instance, the "CAUCASIAN" joke plays very differently within the context of Andrew's interactions with the Homestuck community than outside it -- which may actually make the CC distinction somewhat less relevant for archive readers.
