### ISSUE TITLE
The Sources tab in Inspect Element is borderline unusable

### ISSUE THREAD

**Issue by kobacat** [Bambosh/unofficial-homestuck-collection#320]
When clicking on the Sources tab after opening up Inspect Element, the panel locks up, only moving to the Sources panel after roughly 30 seconds to 2 minutes of waiting. When on the Sources tab, however, nothing can be clicked on whatsoever, being completely stuck on it. Sometimes I've been able to switch back to another tab, but sometimes it doesn't work, and no inputs get registered at all. Using the actual collection is fine, it's just the dev tools that completely freeze.

 - App version v2.0.4
 - Asset Pack version v2
 - Windows 10 version 21H1 (Build 19043)

**Comment by GiovanH** [comment]
Are you using the release version or building locally?

**Comment by kobacat** [comment]
Release version

**Comment by GiovanH** [comment]
The release versions are minified. You can inspect the full sources with the git development version.
