### ISSUE TITLE
Missing Scarecrow King assets in newsposts (plus minor notifications option issue)

### ISSUE THREAD

**Issue by TDBFluff** [Bambosh/unofficial-homestuck-collection#325]
**Missing Scarecrow King assets in newsposts**

**Steps to reproduce the behavior:**
1. Go to MSPA Newsposts
2. Navigate to 25 November 2009
3. On the post that begins with "Hello everybody.", click on the image links for Hussie's Scarecrow King fanart

**Expected behavior**
Fanart images show up as with other image links with assets included in the collection

**Screenshots**
![Collection issue 1](https://user-images.githubusercontent.com/38772676/154827736-ffffe79e-b34a-4204-95b9-b14bda2edc3b.jpg)
![Collection issue 2](https://user-images.githubusercontent.com/38772676/154827738-c827bca9-cd3e-4cef-aa22-ee2967f17c45.jpg)
![Collection issue 3](https://user-images.githubusercontent.com/38772676/154827739-138750b2-4ead-4b06-b45e-a6e2c7209981.jpg)

**Desktop (please complete the following information):**
 - Unofficial Collection V2.0.4
 - V1 Asset Pack + V2 Asset Patch
 - OS: Windows 10

**Additional context**
Just worried that some things the collection links to might be missing from the Asset Pack is all.

Additional but minor issue, when the show minor notifications option is enabled, newspost notifications show up once the first page uploaded on that newspost's date is reached, rather than the last, meaning there are multiple instances of newsposts being unlocked that link to pages that the reader may not have gotten too yet. Usually they link ahead no more than a few pages, so it's not that big a deal, just wanted to mention it.

**Comment by TDBFluff** [comment]
I came here from the report bug option on the collection website, so I didn't see that this was already reported in issues by someone else, apologies for the duplicate issue! That said, I would still suggest taking a look at the issue regarding Minor Notifications for news posts popping up on the first page of the day rather than the last, though I understand if this isn't a particularly important issue to prioritize.

**Comment by GiovanH** [comment]
For testing purposes, what's a good example of a page range for testing the newspost issue?

**Comment by Bambosh** [comment]
This appears to be a one-off case where I forgot to update two URLs to point at the asset pack ( `"newspost_images/scarecrowking1.gif"`and `"newspost_images/scarecrowking2.gif"`). Looks like it's been around since V1. Both images exist in the asset pack at `\archive\social\news`, so we can just adjust the links for now.

**Comment by TDBFluff** [comment]
> For testing purposes, what's a good example of a page range for testing the newspost issue?

Reaching page 393 unlocks a newspost that links to page 397

**Comment by GiovanH** [comment]
Moving notification issue to #331, as there seems to be an explicit bug there
