### ISSUE TITLE
What are locales files for?

### ISSUE THREAD

**Issue by watsuu** [Bambosh/unofficial-homestuck-collection#327]
What are locales files for??
Is it for translation?
How do i use it?
(Sorry for my bad English)
![floder](https://user-images.githubusercontent.com/100065378/154833711-12c1a9fa-7cce-472a-b76a-172ba1cbd8ce.png)
![files](https://user-images.githubusercontent.com/100065378/154833716-2d7c1589-4906-45bc-8b73-43e80e7b07a6.png)

**Comment by GiovanH** [comment]
The locales folder you're seeing there is electron internal and not part of the modding/localization system.
