### ISSUE TITLE
Toby Fox's artist page fails to render on new reader mode

### ISSUE THREAD

**Issue by thecnoNSMB** [Bambosh/unofficial-homestuck-collection#339]
As discussed on Discord, this is due to the lack of an `art` field for his contributions to the Hiveswap Act 2 OST in `music.json`. Bug is present in asset pack V2.

**Comment by Obspogon** [comment]
![image](https://user-images.githubusercontent.com/72287594/156445227-1d6cfa1b-b0ad-411c-a43b-c5522608ee7b.png)
this is what the page looks like

**Comment by GiovanH** [comment]
This is caused by a known issue with the Hiveswap Act 2 music.json hotpatch. @Bambosh

**Comment by triforceganon** [comment]
I still have this issue
