### ISSUE TITLE
Formspring page issues

### ISSUE THREAD

**Issue by GiovanH** [Bambosh/unofficial-homestuck-collection#34]
Re:

> The link to formspring in the 2011-01-16 newspost just links to /formspring which defaults to the top of the andrewhussie formspring, even though it's specifically announcing the mspaintadventures one. This was very confusing for a while, it would be great if the two had separate jump bar URLs links from this point forward were corrected.
(per #18)

The formspring page consists of two separate formspring archives, but they're stored on the same logical page. This means that all links to the formspring page direct to the first (and older) Andrew Hussie page. 

This also means that all the anchorlinks on the mspaintadventures formspring immediately break and send the user back to the top of the root page.

Not confident in a proposed remediation yet, will look into this.

**Comment by Bambosh** [comment]
Easiest solution I can imagine is nesting the formspring two levels deep, something like `/formspring/andrewhussie/andrewhussie2119675960` and `/formspring/mspadventures/question232061478872551861`.

It's worth noting that links to the mspadventures side not working is 100% a bug. Very shameful to let something like that slip.
