### ISSUE TITLE
Since updating the unofficial collection to v2, it hasn't worked properly on my Mac.

### ISSUE THREAD

**Issue by transsludge** [Bambosh/unofficial-homestuck-collection#349]
Since updating the unofficial collection to v2, it hasn't worked properly on my Mac. Panels and other art don't show up. I waited for the next update, but that didn't fix it either. I've tried resetting and relocating the asset packs.

 - Program version: v2.0.5
 - Asset Pack Version: v2
 - OS: Mac
 - log file for troubleshooting just takes me to a page that says "page does not exist", probably because I reset it? I don't know.

**Comment by derpdart** [comment]
same, would like a fix

**Comment by GiovanH** [comment]
Panels not showing up sounds like an asset pack issue. What's the address of the page it takes you to when you try to open log files?
