### ISSUE TITLE
[S] Rose and Dave: Shut up and Jam won't play bolin tracks

### ISSUE THREAD

**Issue by seriousCoolness** [Bambosh/unofficial-homestuck-collection#351]
**Describe the bug**
Even when Controversial Content is enabled, regardless of whether or not new reader mode is on, the Bill Bolin tracks will not replace the default tracks on MSPA page 003620 (or homestuck page 1720).

**To Reproduce**
1. Go to 'settings'
2. Click on 'Enable Controversial Content' (or enable the 'Homestuck - Bill Bolin music' checkbox in the 'controversial content' spoilerbox if new reader mode is off.)
3. Close and Reopen the Homestuck Collection.
4. Navigate to /homestuck/1720/.
5. Cycle through tracks by clicking the beat-player-thingy and notice that none of the tracks are replaced with the Bill Bolin tracks.

**Expected behavior**
The music tracks "Unsheath'd", "Welcome to The New Extreme", "Octoroon Rangoon", "Shatterface", and "Phantasmagoric Waltz" should be replaced with the music tracks "Beatdown (Shitstorm Remix)", "Browbeat", "Beatdown (Trance Praxis)", "Strider Showdown", "Beatdown (Remix v3)" and "Unbound" by Bill Bolin.

**Screenshots**
Yeah pretty sure i cant screenshot audio.

**Desktop (please complete the following information):**
 - Program version: v2.0.5
 - Asset Pack Version: v2
 - OS: Windows 10

**Additional context**
I think it the problem might be caused by the fact that the program cant detect the tracks in the flash because there are multiple, and the actionscript shit that switches the tracks when you click on the beat table probably specifically looks for certain audio filenames.

**Comment by lKomus** [comment]
I've already reported it here: https://github.com/Bambosh/unofficial-homestuck-collection/issues/342
