### ISSUE TITLE
Problem opening Volume 7 text file within the Collection.

### ISSUE THREAD

**Issue by lKomus** [Bambosh/unofficial-homestuck-collection#356]
Pretty much self-explanatory. The Volume 7 text file included in the collection fails to open. Windows gives an error where it can't find a file named "Vol%207.txt".

This is because there is a space contained in the name of the file whereas all the other files have dashes or underscores to avoid this error. Renaming this file would solve the bug.

Using 2.0.5 with Asset Pack v2 using Windows 10 (this might be OS specific.)

**Comment by Obspogon** [comment]
same here
