### ISSUE TITLE
I

### ISSUE THREAD

**Issue by lizzie-wilton** [Bambosh/unofficial-homestuck-collection#357]

**Comment by thecnoNSMB** [comment]
Was this issue opened by mistake?

**Comment by lizzie-wilton** [comment]
> Was this issue opened by mistake?

Yes, and I'm not sure how to delete it. However, this issue was not a mistake and is something I'm keen to get resolved:

https://github.com/Bambosh/unofficial-homestuck-collection/issues/358

**Comment by thecnoNSMB** [comment]
You should be able to close this issue, then.
