### ISSUE TITLE
"Don't style window" option

### ISSUE THREAD

**Issue by GiovanH** [Bambosh/unofficial-homestuck-collection#36]
It would be nice if there were an option to prevent the window frame and UI (tabs, alt menu, etc) from being affected by style changes.

**Comment by Bambosh** [comment]
I took a closer look back into this one in January, having forgotten what utter hell it actually is to resolve. Dunno if it's entirely worth the potential restructuring necessary to get it working? I don't have any strong feelings about it, either way.

**Comment by GiovanH** [comment]
My memory was that https://github.com/Bambosh/unofficial-homestuck-collection/pull/45 was ready to go? Although it's possible I'm forgetting outstanding issues
