### ISSUE TITLE
Updating the collection

### ISSUE THREAD

**Issue by octolingamer** [Bambosh/unofficial-homestuck-collection#363]
That's more of a question than an issue, but how do I update my collection to the 2.0.5 version?

**Comment by Niklink** [comment]
All you need to do is download the 2.0.5 app from the website (https://bambosh.github.io/unofficial-homestuck-collection/) or directly from the github releases page (https://github.com/Bambosh/unofficial-homestuck-collection/releases).

If you're using the same computer, all your save data will carry over.

**Comment by octolingamer** [comment]
Ok thanks
