### ISSUE TITLE
Morse Decoder does not support most Morse-encoded puncutation symbols

### ISSUE THREAD

**Issue by thecnoNSMB** [Bambosh/unofficial-homestuck-collection#366]
According to [Wikipedia](https://en.wikipedia.org/wiki/Morse_code#Letters,_numbers,_punctuation,_prosigns_for_Morse_code_and_non-Latin_variants), test string `.-.-.- --..-- ..--.. .----. -.-.-- -..-. -.--. -.--.- .-... ---... -.-.-. -...- .-.-. -....- ..--.- .-..-. ...-..- .--.-.` should decode to `.,?'!/()&:;=+-_"$@`, but at present only period, comma, and apostrophe are decoded. In Homestuck itself, a colon is encoded on page 5599 as `---...` (which is why this is a bug and not a feature request), there may be more instances in the comic I haven't yet encountered, and mods may include Morse text intended for the decoder that include other symbols. (Note that some of these symbols' encodings overlap with encodings for digraphs and prosigns, if that could be a concern.)

**Comment by Bambosh** [comment]
Resolved in #367
