### ISSUE TITLE
A6A5A1x2 'bent' arrow links rendering incorrectly

### ISSUE THREAD

**Issue by Niklink** [Bambosh/unofficial-homestuck-collection#368]
via interro

'odd rendering error on mac during A6A5A1x2'

![image](https://user-images.githubusercontent.com/25875275/160893068-00a9be26-bb75-4f78-b8d0-3870b83013e0.png)

**Comment by m-jowa1863** [comment]
It's the usage of U+2800 `BRAILLE PATTERN BLANK`. The font is showing an empty Braille grid.
