### ISSUE TITLE
Implement a content warning option

### ISSUE THREAD

**Issue by Stalzak** [Bambosh/unofficial-homestuck-collection#37]
~maybe the real problematic fave was homestuck all along~

new readers going in might have no idea about how real homestuck can get, and while whiplash and shock-value is certainly fun and expected by those who already know about homestuck as a whole, it might be good form to include heads-ups before heading onto certain parts of the story. perhaps it'd even be wiser to have it enabled by default, with a general content warning at the beginning of the comic and on the homepage, with the option to turn future content warnings off.

adding content warnings would ensure a proper ethical and safe consumption for new and returning readers alike. problem is, there is a *lot* to warn for (from the top of my head i could think of "ableism, abuse, alcoholism, bodyshaming, graphic character death, slurs, suicide" but there's probably some more i'm missing... also, *should bill cosby fall under content warnings too?*), and even then i'm not sure how to actually integrate those.

i think the easiest way to go about it would be, on pages before any questionable content, adding a CW box above the next page's link listing all adequate warnings for the section to come. ideally if we're going the extra mile it'd be perfect to also create a quick optional summary of what's actually gonna happen and the option to skip the section altogether if it's not a major flash or anything, but listing all of homestuck's CW will already be a huge task on its own so it might be wise to worry about getting it perfect later.

**Comment by GiovanH** [comment]
It might be a good idea to expose a general interface called `preface` or something that acts like page footnotes but display at the top of the page instead of the bottom, to allow for this sort of thing.

**Comment by JovialKnoll** [comment]
Anything that changes the display of the content from how it was originally displayed should be optional and not default (and ideally done through addons to the content pack, so the community / individuals can decide what they want).

**Comment by JovialKnoll** [comment]
To clarify why in-page CW should be optional and not default: changing the layout / adding spoiling text to a page runs counter to the goal of presenting the comic as it existed, I think.

Also, like, giant wall of CW on a per page basis seems less than helpful. Now, a mod or content editing such that [warnings relevant to particular user] show up on pages might be useful.

**Comment by GiovanH** [comment]
Added preface support as a goal for https://github.com/Bambosh/unofficial-homestuck-collection/issues/28
