### ISSUE TITLE
Openbound ignores all file overrides

### ISSUE THREAD

**Issue by thecnoNSMB** [Bambosh/unofficial-homestuck-collection#373]
I'm developing a mod and routing `assets://storyfiles/hs2/05260/resources/openbound/audio/music/FuschiaRulerQuiet.mp3` doesn't change anything.

**Desktop (please complete the following information):**
 - Program version: 2.0.5
 - Asset Pack Version: v2

**Comment by thecnoNSMB** [comment]
I looked into this further and file overrides of any sort are apparently ignored. Attached is a simple mod that should reproduce the bug.
[test.zip](https://github.com/Bambosh/unofficial-homestuck-collection/files/9128451/test.zip)

**Comment by GiovanH** [comment]
This is weird because openbound overrides definitely work for xml files, as seen with the damara translations.

**Comment by GiovanH** [comment]
Solved it: some openbound urls have version query strings, so the mod needs to read
```js
module.exports = {
    title: "Openbound mod bug demonstration",
    author: "Gibus Wearing Brony",
    modVersion: 0.1,
    routes: {
        'assets://storyfiles/hs2/05260/resources/openbound/backgrounds/load.png?1.0': './load.png',
        'assets://storyfiles/hs2/05259.gif': './load.png',
    }
}
```
See the console for details

**Comment by thecnoNSMB** [comment]
Where in the console would I find the details? I'm not seeing anything of use.

**Comment by thecnoNSMB** [comment]
Ah, you clarified in the Discord. For anyone with a similar problem, the place to look is the Network tab.
