### ISSUE TITLE
Can't get the flash to load

### ISSUE THREAD

**Issue by antleredCouncil** [Bambosh/unofficial-homestuck-collection#382]
I saw on the FAQs to try redownloading the asset pack but I've tried that a handful of times from a couple of the different links on offer and it still hasn't been able to load the flash plugins. I don't think my computer is blocking it so I'm not quite sure what to do.

**Comment by GiovanH** [comment]
Closing as duplicate of #350

(This is still a known problem, but we'll track it in one place. )
