### ISSUE TITLE
Error message on launch, program won’t run 

### ISSUE THREAD

**Issue by Shroom-Kid** [Bambosh/unofficial-homestuck-collection#383]
Today when I tried to run the UHC I got this error message. I don’t know what causes it, but I did uninstall some Java related programs from my computer earlier the same day without knowing what they did, so maybe that has something to do with it?
![BC3CCC46-232C-4105-BBA8-57569D728028](https://user-images.githubusercontent.com/39465551/165008765-2952b728-b553-4504-bc3b-798ab97632d7.png)

P.S. ignore what I named the file directory lol

**Comment by transbimbozone** [comment]
getting the same error as well, reaally weird. here's hoping it's an easy fix lol

**Comment by GiovanH** [comment]
Closing as duplicate of #381

(This is still a known problem, but we'll track it in one place. )
