### ISSUE TITLE
Asset Pack V2 displays as "Damaged Zip Archive"

### ISSUE THREAD

**Issue by octillionbees** [Bambosh/unofficial-homestuck-collection#386]
**Describe the bug**
After downloading Asset Pack V2 from any of the links, the zip file cannot be unzipped, instead displaying the message "Damaged Zip Archive". The Archive Manager isn't even able to view the contents of the zip file.

**To Reproduce**
1. Download the Asset Pack V2 using either the Media Fire Mirror or the Magnet link.
2. Attempt to  extract the files to any location.
3. See error.

**Expected behavior**
When extracting the files, they should be extracted to an uncompressed folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/65750561/167501223-f8065543-5543-4f6a-ad12-c914d80d6c21.png)

**Desktop (please complete the following information):**
 - Program V2.0.5
 - Asset Pack Version 2
 - OS: Linux [Pop!_OS 22.04 LTS]

**Comment by soulwa** [comment]
this is probably the same as #353, tl;dr is to run `zip -FF` on the file as specified in that issue and you should have a functional archive.

**Comment by GiovanH** [comment]
Closing as duplicate
