### ISSUE TITLE
i cannot see any of the images

### ISSUE THREAD

**Issue by glassyeggs** [Bambosh/unofficial-homestuck-collection#396]
for some reason, i cant see any images for the comic. 
![please just let me read homestuck im gonna scream oh my god](https://user-images.githubusercontent.com/107722691/174399903-53b7134d-bad0-4a73-9e4e-e13fe339b9fb.png)
i am on windows and im using asset pack v2 and the most recent program version. i am very confused why this isnt working, because for one of my friends the images do load so i am confused.
it looks the same for this page and all the previous ones too.

**Comment by GiovanH** [comment]
Verify your asset pack.

**Comment by glassyeggs** [comment]
i dont know how i fixed it, but someone helped me. i kept opening the wrong asset pack i think so i got it now??? yay
