### ISSUE TITLE
colours and mayhem album covers do not appear

### ISSUE THREAD

**Issue by gabman15** [Bambosh/unofficial-homestuck-collection#4]
![image](https://user-images.githubusercontent.com/32818424/97232678-fb70f180-17b3-11eb-9f1e-8b3885a390f6.png)

as title says. The cover art of the two colours and mayhem albums in the music database do not display even though they exist in the assets folder. I am running the linux version.

**Comment by Bambosh** [comment]
I suspect this is probably due to case-sensitive paths on your OS. Try renaming the coloUrs and mayhem folders in `{Asset Dir}/archive/music` to make the capital U lowercase.

**Comment by gabman15** [comment]
> I suspect this is probably due to case-sensitive paths on your OS. Try renaming the coloUrs and mayhem folders in `{Asset Dir}/archive/music` to make the capital U lowercase.

Yup that fixed it thanks!

**Comment by SirAxolot** [comment]
Can you implement a fix in the project itself?
I can fix it myself (i think) but a hotfix in the next update would be a good idea.
