### ISSUE TITLE
Using |AUTHORLOG| in the settings page breaks scratch theme, others

### ISSUE THREAD

**Issue by GiovanH** [Bambosh/unofficial-homestuck-collection#41]
Original title: The "text override" demo box is unreadable with the scratch theme

Admittedly, humorously.

**Comment by GiovanH** [comment]
The issue here seems to be that |AUTHORLOG| looks pretty on the MSPA theme but isn't supported by all styles.

**Comment by GiovanH** [comment]
@Bambosh since you closed the PR that fixes this issue

> A better solution would be to change the style of the box to be readable with the scratch theme. Probably by changing the background black, but if that causes problems we can just force the text to be black.

The fundamental problem is *not* that the background happens to be the wrong color. The problem is that the example text is rendered with the very specific |AUTHORLOG| directive, which is only actually ever defined for one theme, the MSPA default. 

A very obvious use case of the example box is setting the theme manually to see how text looks on harder-to-read themes. For this to be meaningful, though, the example text needs to be rendered *correctly*, as text will actually be rendered in that theme. Arbitrarily styling it with manual backgrounds subverts the point of the test box. 

Admittedly, the authorlog style looks very nice on the MSPA theme. Maybe the whole <pagetext> element should be wrapped in a border on the settings page, to give it that nice look? But using the |AUTHORLOG| directive creates many extra problems, like this one.

**Comment by GiovanH** [comment]
In general, a big problem with |AUTHORLOG| is that it forces the background to be white, regardless of the actual narration. This is especially bad for the scratch theme, but it's also bad for *everything else*, because it gives the text different contrast on the demo page than it actually has in the story.

**Comment by GiovanH** [comment]
I have updated https://github.com/Bambosh/unofficial-homestuck-collection/pull/42 to include a pesterlog as well as narration, so it is easy for the user to test both cases. This is especially useful for the scratch theme and others that directly manipulate log boxes.

**Comment by Bambosh** [comment]
PR merged
