### ISSUE TITLE
not a bug just need help unziping asset pack on mac

### ISSUE THREAD

**Issue by nope1game** [Bambosh/unofficial-homestuck-collection#410]
how do i unzip the file on mac?

**Comment by nope1game** [comment]
do i use i different mirror?

**Comment by nope1game** [comment]
![Screen Shot 2022-07-26 at 2 27 16 PM](https://user-images.githubusercontent.com/108080653/181083664-21d6d6f4-492a-4f13-bf46-95990e7efbec.png) This is what the error message says.

**Comment by thecnoNSMB** [comment]
it's probably too large for your default unzipper to handle, try using 7zip
