### ISSUE TITLE
French version of Homestuck.

### ISSUE THREAD

**Issue by LolaStarly** [Bambosh/unofficial-homestuck-collection#414]
**Is your feature request related to a problem? Please describe.**
Hello, my name is Lohn and i have an issue. I want to show Homestuck to my friends, but there is no such thing as a "French Mod" on the Unofficial Homestuck Collection.

**Describe the solution you'd like**
I would like a french mod for the UHSC. 

**Describe alternatives you've considered**
I've already started translating Homestuck, so i thought i could share my translation, and hopefully make a mod out of it.

**Additional context**
https://cdn.discordapp.com/attachments/704049287524253696/1003465022644699217/unknown.png
![image](https://user-images.githubusercontent.com/65873317/182053619-eec5dd5e-a51c-481c-aa39-f728f5f724ef.png)

Thank you for taking the time to read this issue. 
With kind regards,
Lohn.

**Comment by Shaddytheguy** [comment]
There is an ongoing FR translation of Homestuck [here](https://mspfa.com/?s=47230&p=1) updated as recently as 2 days ago, you could probably get in contact with them.
