### ISSUE TITLE
already fixed while surfing through other issues!! sorry for inconvenience !! // issues opening the app

### ISSUE THREAD

**Issue by hollylf** [Bambosh/unofficial-homestuck-collection#415]
### _edit: i managed to solve this. sorry for not scrolling enough through the issues board! my mistake._

**Describe the bug**
hello! I seem to be having issues with opening the app. I managed to open it the first time, I entered the page I was on in the new reader configuration and all the other things you have to do first. then, I finished downloading the assets and set the folder in the app, and clicked the "all done!" button (or something along the lines of that). an error appeared, the app closed and i didn't pay much attention to it, thinking it was just a simple bug, so i tried to open the app once more and found myself unable to. the problem is not even an error message appears, it just appears to be loading for a few seconds and then nothing happens.
I tried checking the compatibility in the 'properties' of the app, but I couldn't make any progress by myself. 

**To Reproduce**
1. Double-click on 'The Unofficial Homestuck Behaviour', or right-click in order to open the app.
2. Nothing happens.

**Expected behavior**
I simply expected the app to open normally like a few moments before.

**Desktop (please complete the following information):**
 - App V2.0.5, displayed on the website. I have also just attempted to open the V2.0.6 to no avail.
 - Asset Pack V2, downloaded through mediafire (mirror 1)
 - OS: Windows 10, 64bit

**Additional context**
I use winrar to unzip files. however I'm not sure if that is relevant

**Comment by GiovanH** [comment]
For the record, what was the solution?
