### ISSUE TITLE
Homestuck Album/Track Art

### ISSUE THREAD

**Issue by DewOnTheGrass** [Bambosh/unofficial-homestuck-collection#421]
**Is your feature request related to a problem? Please describe.**
When the Homestuck Bandcamp was revamped, VIZ removed not only the thereafter-unused cover arts of half of the bundled albums, but also every individual track cover.

**Describe the solution you'd like**
I'd like to see an archive of this art in the UHC. If someone is feeling particularly ballsy, I'd be thrilled to see a way to integrate the art into a user's local copy of Homestuck discography.

**Additional context**
The repeated tracks show the modern download's lack of unique track art.
![Repeated tracks show lack of unique artwork](https://user-images.githubusercontent.com/36544994/184646931-8cc92116-93fd-4309-b60c-43840f25293a.jpg)

**Comment by GiovanH** [comment]
In what cases is the archive missing this?

**Comment by thecnoNSMB** [comment]
The archive already contains track art on individual song pages.

**Comment by chitinlink** [comment]
How about a separate asset pack for music?

**Comment by DewOnTheGrass** [comment]
> The archive already contains track art on individual song pages.

Oh! You're absolutely right... I didn't look hard enough. Thank you! I'll start embedding those in my music library!

**Comment by thecnoNSMB** [comment]
> How about a separate asset pack for music?

I doubt this will happen officially, since Homestuck music is still officially for sale.
