### ISSUE TITLE
MSPA Newsposts not loading

### ISSUE THREAD

**Issue by owen-wilson** [Bambosh/unofficial-homestuck-collection#423]
**Items not loading**
Clicking on the MSPA Newsposts hyperlink (homepage) results in a blank screen and no content is shown

**To Reproduce**
1. Scroll to bottom of homepage
2. Click on MSPA Newsposts
3. See error

**Expected behavior**
I expected to see an archive of the MSPA Newsposts as they were posted from June 2007 to April 2018

**Screenshots**
![Screenshot (215)](https://user-images.githubusercontent.com/47800485/186572633-7b20b4c9-9135-4ee7-8cc3-70fa6774da07.png)

**Desktop (please complete the following information):**
 - Application v1.0.0
 - Asset File v2
 - Windows 10

**Additional context**
There is a similar issue on Dave Strider's blog with the Sweet Cred archived minigame under the post "some candy company ripped me off" (February). Clicking most of the menu options results in no content other than a solid background (screenshots provided), but you can still navigate back to the homepage or other (probably blank) options. I didn't know if this was in some way related to the focal issue or if this was intended due to file space.

"What's New" 
![Screenshot (216)](https://user-images.githubusercontent.com/47800485/186573375-aef8f592-9480-4f6b-9f6f-2968845ac104.png)

"Sweets and Toys" 
![Screenshot (217)](https://user-images.githubusercontent.com/47800485/186573488-5099dcb6-b437-4e20-a874-e8fa8a4e330f.png)

"Games Arcade" 
![Screenshot (218)](https://user-images.githubusercontent.com/47800485/186573588-ab49732c-5366-4101-b370-2cfde789df40.png)

"Cool Downloads"
![Screenshot (219)](https://user-images.githubusercontent.com/47800485/186573647-17e91719-e233-4ed5-a2a8-485331401116.png)

"Visitor Art Gallery" 
![Screenshot (220)](https://user-images.githubusercontent.com/47800485/186573696-9e8f836a-c793-4b56-8c5e-c036a95df5c9.png)

**Comment by GiovanH** [comment]
Please post your log file.

**Comment by Archonic944** [comment]
I can confirm that the Sweet Cred thing is real. It's happening for me too.
Look, I know this isn't, like, the MOST IMPORTANT thing, but still...

**Comment by GiovanH** [comment]
News is working on the latest version. 

As for Sweet Cred, unfortunately a lot of the sub pages are lost media. We don't have them :(

**Comment by Archonic944** [comment]
Unfortunate...
