### ISSUE TITLE
The issue I am having here is with downloading this on linux. I am quite new to it and have no idea what I'm supposed to do to download it and it's getting frustrating. If possible, a youtube video on how to download and get it up on linux would be appriciated. If not I will be trying to get more familiar with linux, but I most likely will end up dropping this despite how nice it would be to get the original homestuck experience. :( 

### ISSUE THREAD

**Issue by TheBCast** [Bambosh/unofficial-homestuck-collection#425]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bodertz** [comment]
This is not really the best place for this discussion.

The general process is to download this:

https://github.com/Bambosh/unofficial-homestuck-collection/releases/download/2.0.5/unofficial-homestuck-collection-2.0.5.tar.gz

And then download this:

https://www.mediafire.com/file/ibuq7kts2ttkow1/Asset+Pack+V2+-+The+Unofficial+Homestuck+Collection.zip/file

And then extract both archives, run the `unofficial-homestuck-collection` file from the first archive, and follow the instructions to point it to the extracted Asset Pack directory.

However, you may need to run the `unofficial-homestuck-collection` file with `--no-sandbox` as an argument.  Is that something you would know how to do or would you need that explained further?
