### ISSUE TITLE
On X2Combo pages right Go back navOption have empty class

### ISSUE THREAD

**Issue by AssisTENTUtopist** [Bambosh/unofficial-homestuck-collection#426]
**Describe the bug**
For some reason template in [x2ComboNav.vue ](https://github.com/Bambosh/unofficial-homestuck-collection/blob/main/src/components/SpecialPages/x2ComboNav.vue) has class startOver for both pages and class goBack only for the left one:
```
<li v-if="pageNumber.p !== '1'">
    <a :href="startOverUrl" class="startOver">Start Over</a>
</li>
<li v-if="'previous' in thisPage">
    <a :href="backUrl" :class="{goBack: isLeftPage}">Go Back</a>
</li>
```

**To Reproduce**
1. Go to /mspa/7700
2. Inspect "Go Back" on the right page
3. See empty class

**Expected behavior**
Similar behaviour to startOver

**Screenshots**
Noticed it while trying to translate NavOptions via vueHooks mounted(): 
![image](https://user-images.githubusercontent.com/24652029/187303697-26444799-b3fc-4f65-a33c-5be48d1ae004.png)

**Desktop (please complete the following information):**
 - Application version: v2.0.5
 - Asset pack version: v2
 - Windows 10

**Comment by GiovanH** [comment]
This is not the case with the vanilla app.
