### ISSUE TITLE
Javascript error?

### ISSUE THREAD

**Issue by angelCakes1** [Bambosh/unofficial-homestuck-collection#429]
**Describe the bug**
Application itself wont open anymore.

**To Reproduce**
1. Downloaded both the asset pack and the application
2. Locate asset pack
3. Loads for a minute
4. Pop-up about an error with the Javascript, closes
5. Actual application no longer opens, double click and it loads then doesnt finish, doesnt even open

**Desktop (please complete the following information):**
 - V2.0.5
 - Asset Pack Version 2
 - Windows

**Comment by GiovanH** [comment]
What was the error?

**Comment by silkough** [comment]
Hi! I think I'm having the same issue here; the error description says ''something went wrong installing the 'sharp' module''.

**Comment by leilaisdying** [comment]
Yea this same thing happened to me!!! Did you ever find a solution?

**Comment by thecnoNSMB** [comment]
This is a known issue: #381
