### ISSUE TITLE
Additional Formspring posts

### ISSUE THREAD

**Issue by TwilightVelvet** [Bambosh/unofficial-homestuck-collection#430]
**Is your feature request related to a problem? Please describe.**
While the Collection notes that the Formspring posts were made from "Feb 2010 - Aug 2011", the application only appears to show those up to January 2011, before the "mspadventures" Formspring account became active.

**Additional context**
Link to a website archiving all of the Formspring posts: [wheals.github.io](https://wheals.github.io/formspring/formspring.html)

**Comment by GiovanH** [comment]
Both accounts are available in the app; there is a button to click.
