### ISSUE TITLE
App error message after selecting asset pack

### ISSUE THREAD

**Issue by zcat8000** [Bambosh/unofficial-homestuck-collection#431]
Describe the bug
Error message after selecting asset pack, 
Application itself wont open anymore.

To Reproduce

1.Downloaded both the asset pack and the application
2. Everything in the intro working fine
3. Selected the asset pack v2 folder when prompted in the app
4. Hitting Next caused the app to crash and the below error message to pop up
5. Cannot open the program at all again to change or fiddle with the settings or anything, just keeps giving the same error message.

V2.0.5
Asset Pack Version 2
Windows 11
same issue with the prerelease V2.0.6  version i tried after getting this error.

**Screenshots**
2.0.5 error message:
![error mssg](https://user-images.githubusercontent.com/113543612/190216794-69bd8ed8-1a1c-431b-bde6-f3f8ed64debe.png)

2.0.6 error message:
![error mssg](https://user-images.githubusercontent.com/113543612/190216001-b2546b30-9486-4d68-8d91-1e2d71bd4bcf.png)

(sorry if i did anything wrong this is the first time ive ever left a messege on github)

**Comment by GiovanH** [comment]
You don't have permission to read one of the required files. Is your antivirus blocking you? Is the file open in another process?

**Comment by zcat8000** [comment]
> You don't have permission to read one of the required files. Is your antivirus blocking you? Is the file open in another process?

That was it, thank you!!! I got it to work by moving the folders. im on a new computer and _was_ a bit confused why i kept needing to give permission to move the files around in there-__-
