### ISSUE TITLE
I can't see emojis in pesterlog 

### ISSUE THREAD

**Issue by Lein7** [Bambosh/unofficial-homestuck-collection#433]
**Describe the bug**
Emojis in the pesterlog are not loading. 

**To Reproduce**
1. Go to 'every page that has an emoji on the pesterlog'
2. Click on 'open the pesterlog'

**Screenshots**
![Captura de pantalla 2022-09-15 193900](https://user-images.githubusercontent.com/113560892/190521264-e1440b2a-7b0c-4c74-a805-9920577575b2.png)

**Desktop (please complete the following information):**
 - Program version: v2
 - Asset Pack Version: v2
 - OS: [Windows]

**Additional context**
Its every emoji that appears in the chat, not only dirk's shades.

**Comment by GiovanH** [comment]
Double-check your asset pack installation.
