### ISSUE TITLE
Page 3042 has seemingly escaped HTML tags

### ISSUE THREAD

**Issue by gBasil** [Bambosh/unofficial-homestuck-collection#434]
![image](https://user-images.githubusercontent.com/57513430/192128846-e870d228-e0b0-48f7-8f7f-1d1dc1289e09.png)

**Comment by Sixthhokage1** [comment]
It's intentional: 
> Also, I remember some people thinking those \<black> \</black> tags were a formatting error. No, it's just a joke.

**Comment by gBasil** [comment]
> It's intentional: 
> 
> > Also, I remember some people thinking those \<black> \</black> tags were a formatting error. No, it's just a joke.

Gotcha, thank you!
