### ISSUE TITLE
Sound control. I just want to mute the sound please

### ISSUE THREAD

**Issue by erauqs4** [Bambosh/unofficial-homestuck-collection#435]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thecnoNSMB** [comment]
This should be easily doable through your system volume control.

**Comment by erauqs4** [comment]
I have a Mac so there's no system volume control, and the third-party
software I tried is unable to change the volume of the collection T_T
