### ISSUE TITLE
Accessability issue with Rose's FAQ

### ISSUE THREAD

**Issue by Proxiehunter** [Bambosh/unofficial-homestuck-collection#437]
Someone reading Homestuck currently has pointed out that Rose's FAQ is difficult for them to read in part because of the font used as well as the size. And it's not formatted as _text_ so they can't just copy paste it. If there's a way to put a link on the FAQ pages to a text version that would obey the font settings of the user it would improve accessibility for those with poor vision or disorders effecting their ability to read long passages of text. I would also recommend this more accessible text version do away with the visual clutter of the ==== used to separate out headers. 

A text version of the entire faq already exists [here](https://mspaintadventures.fandom.com/wiki/Rose%27s_walkthrough) so no work is required to type it out, the sections just need copied to where ever you would put them to make this work.

**Comment by Bodertz** [comment]
This is perhaps overkill for your friend's case, but the mod "tuhc-readmspa" [1] includes a transcript of the walkthrough under the image.  It will, however, also include transcripts for things like flash games.


[1] https://github.com/GiovanH/tuhc-readmspa

**Comment by GiovanH** [comment]
The readmspa transcripts are the current solution for this.
