### ISSUE TITLE
asset pack

### ISSUE THREAD

**Issue by Sburbian** [Bambosh/unofficial-homestuck-collection#445]
i have downloaded and redownloaded the asset pack (as well as the app itself) listed multiple times but whenever i use the app, it doesn't appear to register that the file or application listed as the one to use in the app is even there. i have tried even going from the asset folder and using 'open with' but the app still will again ask for the file which it doesn't show.

i am not sure if there is something i am doing wrong? i can try again so i have screenshots, if needed, but i would really love to use the app and the asset pack as directed.

**Comment by GiovanH** [comment]
You do not open the asset directly with the application, you extract it. Please re-read the installation instructions.
