### ISSUE TITLE
i can't run the program 

### ISSUE THREAD

**Issue by gege-11** [Bambosh/unofficial-homestuck-collection#448]
i downloaded the app ,and extracted the files but when i try to run the program i always get this error message 
<img width="423" alt="Screenshot 2022-11-29 100931" src="https://user-images.githubusercontent.com/119395392/204452242-763500fa-268d-4284-a81d-c8219ad4c29c.png">
i don't know why i got this , i used the correct download link for the system and i tried to delete it and redownload it multiple times but still didn't work ,it worked fine on my old laptop (note both my past and current laptops use windows 10) so i really have no clue why it didn't work

**Comment by thecnoNSMB** [comment]
This is a known issue. Please see #381 for help.
