### ISSUE TITLE
Flash pages with retcon tags do not load high quality audio, whether or not the option is enabled

### ISSUE THREAD

**Issue by aubymori** [Bambosh/unofficial-homestuck-collection#451]
**Describe the bug**
Any Flash page with retcon tags (`"R1"`, `"R2"`, etc.) that also has a corresponding HQ version of its SWF (`"HQ"` tag) does not load the HQ version, whether or not the high quality Flash option is enabled. The most notable example of this is `[S] Wake.`, which has its own retcon file, and suffers from this bug.

**To Reproduce**
1. Open Unofficial Homestuck Collection
2. Enable the option for high quality Flash audio if it isn't already enabled
3. Go to `/homestuck/3297` (or `/mspa/005197`)
4. The audio is still low quality, despite the fact that the option for high quality audio is enabled.

**Expected behavior**
The high quality audio version of the SWF should load.

**Desktop (please complete the following information):**
 - Program version: v2.0.6-pre
 - Asset Pack Version: v2
 - OS: Windows 10 IoT LTSC Enterprise 2021 (10.0.19044)

**Comment by GiovanH** [comment]
Confirmed [S] Wake does not behave properly with HQ audio and no retcons:

Actual:
```
[info]  /mspa/005197 - [S] Wake.
[info]  Getting flash props for 03294 /storyfiles/hs2/03294/03294.swf
```

Expected: 
```
[info]  /mspa/005197 - [S] Wake.
[info]  Getting flash props for 13294 /storyfiles/hs2/13294/13294_hq.swf
[debug] audioInit
[debug] Creating audio
[info]  Getting audio tracks for /storyfiles/hs2/13294/13294_hq.swf /storyfiles/hs2/13294/13294.swf [{…}, __ob__: Observer]
[info]  Adding track /storyfiles/hs2/13294/13294.mp3
[info]  {…}
[debug] audioStart
[debug] Playing audio (undefined)
```
