### ISSUE TITLE
"Something went wrong with the 'sharp' module" error when starting the program

### ISSUE THREAD

**Issue by Realtent** [Bambosh/unofficial-homestuck-collection#452]
Whenever I try to boot up The Official Homestuck Collection application, from a shortcut or in the folder, it gives me this error:
![image](https://user-images.githubusercontent.com/121059661/208510650-10139300-2359-4392-8ae5-1face6edf78b.png)
I have uninstalled and reinstalled the application folder (not the assets folder yet) and the issue persists.

I reproduce this when I try to start the application.

![image](https://user-images.githubusercontent.com/121059661/208510908-de65e612-f159-474a-a30a-afde2ed543b9.png)

Just downloaded the latest version of the application, and have the Asset Pack V2
Windows OS version 22000.1335

I was uninstalling windows apps earlier, and so I may have uninstalled something important, but they weren't considered essential by my computer, so I'm not sure.

**Comment by thecnoNSMB** [comment]
This is a known issue, please see #381
