### ISSUE TITLE
[Windows 11] Image displayed improperly with display zoom set >100%

### ISSUE THREAD

**Issue by Netherfield** [Bambosh/unofficial-homestuck-collection#457]
Picture on page 249 is displayed improperly and the text is unreadable when Windows' display zoom setting is anything higher than 100%

It probably happens with other pages but I've tested only page 249 on 125, 150 and 175 zoom.

Version V 2.0.5
Asset Pack V 2
Windows 11 22H2 build 22621.1105

**Comment by GiovanH** [comment]
What do you mean by "improperly"? Do you mean it's aliased differently than expected? What does it look like?

**Comment by sanctuary-pkg** [comment]
![125zoom](https://user-images.githubusercontent.com/66134263/222674832-8e10abe7-b0c8-4454-9014-7027bc333a7c.png)

The text is unreadable for me on any zoom that isn't 100%. The screenshot is on 125% zoom but it looks similar on 150 and 175.
It's being displayed on a 1920x1080 display ( Samsung Galaxy Book2 Pro 360)

The screenshot is on
Version V 2.0.5
Asset Pack V 2
Windows 11 Home 22H2 build 22621.1265

**Comment by dpathakj** [comment]
@sanctuary-pkg, that's a bit like what I see on a similar display (1080p 14" laptop display, albeit different OS/laptop). Try disabling pixelated image scaling in the settings menu. For me, the text is very sharp with that setting off.

**Comment by thecnoNSMB** [comment]
This does reproduce on my copy, but the text in the original image is already fairly low resolution. As a workaround I would suggest using the [readmspa mod](https://github.com/GiovanH/tuhc-readmspa) and reading the transcript, or maybe asking the [Plaintext Images](https://github.com/Squornshellous-Beta/Plaintext-Images) developer to possibly convert this page to CSS. (Additionally, I think Flare might have something like that in development but I don't know for sure.)

**Comment by GiovanH** [comment]
The solution for this is to disable the pixelated image scaling option.
