### ISSUE TITLE
Incorrect Song playing in Album

### ISSUE THREAD

**Issue by AmbientRainfall** [Bambosh/unofficial-homestuck-collection#458]
Flying Car from the One Year Older album doesn't play the song it's supposed to, it plays Fly from the Mobius Trip and Hadron Kaleido album. The Bandcamp and YouTube links are correct though.

Here's a screenshot

![image](https://user-images.githubusercontent.com/123280183/213897293-78a20f89-be1a-4294-a925-6a639358121e.png)

**Comment by GiovanH** [comment]
This has been fixed on develop.
