### ISSUE TITLE
plugin failed to load

### ISSUE THREAD

**Issue by Metal228** [Bambosh/unofficial-homestuck-collection#459]
every [S] page doesnt work and screen with the ,,plugin failed to load" text appearing instead. Maybe that's because i have 32 bit version of windows and it's some sort of bug......? (i have installed and unzipped the asset pack v2). Or maybe i'm just too stupid and don't understand how stuff works there who knows

**Comment by GiovanH** [comment]
You have not reported any of the necessary information. What OS? 32 bit version of Windows 10? Attach your log files.

**Comment by Metal228** [comment]
Oh I'm really sorry for that. 
I have 32 bit version of windows 10 pro (sadly can't show the images. At least right now) 
Once again, I'm very sorry for the inconvenience caused.

**Comment by Metal228** [comment]
Uuuuuuhhh sooo. Do I need to write a new issue or what
