### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by Grafcube** [Bambosh/unofficial-homestuck-collection#470]
I have packaged TUHC for flatpak. You can find the manifest and appstream xml [in this repo](https://github.com/Grafcube/unofficial-homestuck-collection-flatpak).

According to the flatpak [app submission guidelines](https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do):
> Flathub is primarily intended as a service that is used by app developers to distribute their apps. Our goal is to give developers control of their apps and to allow them a closer relationship with their users without middlemen getting in the way. However, as part of setting up Flathub, some applications are being distributed on Flathub without the involvement of their developers. We would prefer that these applications are controlled by their authors.

For this reason, I am opening an issue here first. If you do not want to maintain the package I don't mind managing it and updating it for new releases on Flathub.

If everything looks good the package can be published and a Flathub link can be put in the README and the website.

Please let me know if there are any changes I have to make.

**Comment by GiovanH** [comment]
@Bambosh If we're keeping the repos under your name, you should run through this. Otherwise I'll be happy to.

**Comment by Grafcube** [comment]
@Bambosh @GiovanH  Any updates on this? The package is complete and works correctly. I would be willing to maintain the package myself, I just want confirmation.

**Comment by Bambosh** [comment]
Really really sorry for letting this one slip so long! There's no problem at all if you want to host it.
