### ISSUE TITLE
Corrupt Assets?

### ISSUE THREAD

**Issue by MatiasParedes00** [Bambosh/unofficial-homestuck-collection#473]
**Describe the bug**
I'm trying to install the browser on Arch Linux (btw :P) and the app itself (AppImage) runs just fine, but I can't unzip the assets for some reason. I tried both a GUI based solution (Xarchiver) and a console one (unzip) with no luck. I also tried downloading from both Mediafire and the torrent. I promised my girlfriend I'll read Homestuck and I don't wanna disappoint her, so any guidance or help would be appreciated

**To Reproduce**
1. Download the Assets (from any source)
2. Try to unzip it
3. The archiver gives error due to supposed corrupted file

**Expected behavior**
The Assets unzipping correctly and with no errors

**Screenshots**
[Output of Commands](https://imgur.com/a/gqCfgtO)

**Desktop (please complete the following information):**
 - Program version: 2.0.5
 - Asset Pack Version: V2
 - OS: Arch Linux, fully updated

**Additional context**
The assets were downloaded today (Tuesday 21th of February 2023). The browser itself runs just fine. The first attempt of downloading the assets failed because the internet went off for a moment, but I don't think it affected it in any way. I downloaded both from Mediafire and the torrent, and the torrent gave no errors. Both Xarchiver and unzip couldn't unzip the file, for some reason

**Comment by GiovanH** [comment]
Please try again with 7zip.

**Comment by MatiasParedes00** [comment]
Yeah, it was it. I didn't have it installed as I usually don't use it too often. Thanks! ^^
