### ISSUE TITLE
next page button (==> and all other next buttons) stop working after several or even one page

### ISSUE THREAD

**Issue by thecloudking** [Bambosh/unofficial-homestuck-collection#475]
after reading several pages, or even only one page, the next button (the ==> button) stops working. i cannot go to the next page, i cannot go backwards to a previous page, i cannot go to another tab or open a new tab. i'm stuck on the page i just finished reading. pesterlogs also cannot be opened if set to be closed by default. the problem is fixed after closing and re-opening the app, but then happens again minutes later

Program version 2.0.5
 OS:  Windows 10

currently running the unofficial collection with several mods installed/active. these mods are:
bandcamp player
puzzlestuck
homestuck POV cam port
damara translation
morse code
social links
JOHN DO THE WINDY THING

hardware acceleration is off, arrow key navigation is on but does not work when the page navigation gets stuck like this. reading experience is set to replay mode if that matters. UI and page theme are both cascade, font is open dyslexic with chat paragraph spacing. i think that's about it for settings i have changed

**Comment by thecnoNSMB** [comment]
In my experience this is probably caused by the POV cam port. Does disabling that mod fix the issue?

**Comment by Tofutush** [comment]
yeah, the pov does mess with the buttons. you can try directly changing the number in the top url bar.

**Comment by thecloudking** [comment]
sorry for not replying! i had surgery and completely forgot about the
report i made. disabling POV cam did seem to work, which is a shame because
that was a really interesting mod. thanks for your help!
