### ISSUE TITLE
Asset pack unopenable

### ISSUE THREAD

**Issue by AlmaBeaSophia** [Bambosh/unofficial-homestuck-collection#479]
**Describe the bug**
When trying to extract asset pack, an error "Damaged Zip archive" occurs

**To Reproduce**
1. Download the current version of the asset pack.
2. Attempt to extract it using the Info-ZIP tool.

**Expected behavior**
When trying to extract asset pack, an error "Damaged Zip archive" will occur

**Screenshots**
![image](https://user-images.githubusercontent.com/125508272/222981979-ec38d504-314f-4636-911d-bf517a2bc357.png)

**Desktop (please complete the following information):**
 - Asset pack version 2
 - OS: Fedora Linux version 37

**Additional context**

**Comment by GiovanH** [comment]
Try 7-zip.
