### ISSUE TITLE
SBAHJ linkhole links not formatted as HTML

### ISSUE THREAD

**Issue by Bodertz** [Bambosh/unofficial-homestuck-collection#480]
**Describe the bug**
The "linkhole" on SBAHJ pages contains links to other pages of SBAHJ.  Instead of being interpreted as HTML, the link titles are interpreted as text, so comic 20, for example, shows up as [1] instead of [2]:

[1] CO\<b>MIC #​20: CHECK OUT THUS HOT NEW MORC\</b>H..........

[2] CO**MIC #​20: CHECK OUT THUS HOT NEW MORC**H..........

This can be fixed by changing:

https://github.com/Bambosh/unofficial-homestuck-collection/blob/2982d7fd60a41029f7d9f90f60f47ed0db32c483/src/components/Comics/sbahj.vue#L32

to:

```vue
<a :href="comic.url" v-html="comic.title" :key="`comic${i}`"/>
```

I don't know enough to know if doing that is too much of a security concern, so someone else will have to decide that.

---

 - Program version: v2.0.7
 - Asset Pack Version: v2
 - OS: Linux version 6.0.12

**Comment by GiovanH** [comment]
Fixed bd8ac17fa8772a5baa05c582c77fee4e7061f43b
