### ISSUE TITLE
Incorrect image link in formspring answer

### ISSUE THREAD

**Issue by numberQ** [Bambosh/unofficial-homestuck-collection#483]
**Describe the bug**
In formspring answer `/formspring/andrewhussie550488999`, the media link tries to open `/archive/formspring/00958_1.gif`. However, in the V2 asset pack, it should be `/archive/social/formspring/00958_1.gif`. As is, an error appears instead.

**Screenshots**
![image](https://user-images.githubusercontent.com/6134338/226088991-da005b8a-d685-4fda-b615-bfa8d235a688.png)

**Desktop (please complete the following information):**
 - UHC 2.0.5
 - Asset Pack V2
 - OS: Windows 10

**Comment by thecnoNSMB** [comment]
I can successfully reproduce this in my copy.

**Comment by GiovanH** [comment]
Fixed last year with 9871e3b42aff1fcc60e9028e912f10485b58aa6b.
