### ISSUE TITLE
cant view plugins

### ISSUE THREAD

**Issue by clownbae** [Bambosh/unofficial-homestuck-collection#485]
**Describe the bug**
im not sure what it is but all the plugins arent loading, i checked other gif/flash pages and its the same.

**Expected behavior**
i expected to view the page i was on, as thats why i downloaded the unofficial collection to have an easier time reading

**Screenshots**
![image](https://user-images.githubusercontent.com/128587693/226856355-9d582b72-11bf-4993-b975-dbd6b6af763d.png)

**Desktop (please complete the following information):**
 - Program version The.Unofficial.Homestuck.Collection-2.0.5-ia32-win
 - Asset Pack Version asset pack v2
 - OS: [Windows 10 version 22H2]

**Comment by GiovanH** [comment]
Are you running windows 32 bit? You probably want the other executable.
