### ISSUE TITLE
New Controversial Content Option: Ableism

### ISSUE THREAD

**Issue by foreverWIP** [Bambosh/unofficial-homestuck-collection#5]
First of all, I'd like to say I really appreciate the work put into this thing. This compendium is a clear demonstration of how a determined community can achieve amazing things.
That said though, while I appreciate the work that's already put in to deal with questionable content in the archive, it still has a way to go. One example is the amount of ableism present throughout Homestuck, and in a few other areas. Examples include semi-frequent usage of the r-slur, as well as usage of mental illness names as pejoratives. I'm aware it wouldn't be as easy as making a toggle and switching words out (as there are various audio files and Flashes that contain it as well), but if some way of avoiding or warning of this content could be offered as an option, it would be much desired.

**Comment by Bambosh** [comment]
I haven't included an option to censor slurs by default, but I intentionally designed it so people can make edits like this and circulate them personally. Homestuck's full text is stored in plain HTML in `{Asset Pack}/archive/data/mspa.json`, and can be edited + redistributed however you want. [Check out this project someone kicked off to filter out slurs!](https://twitter.com/AltUniverseWash/status/1320759511242649601?s=20)

**Comment by Proxiehunter** [comment]
It would be nice to see an option so I could install that and have a button to toggle it on and off. Right now I either have to have the original installed _or_ the slur free version and I'd prefer easy ability to toggle between the unexpurgated version and the updated one with one easy click. Not sure if that's something they have to do on their end, an option that needs to be made available in a future build, or something you have to work together to accomplish.

**Comment by Bambosh** [comment]
A more advanced method of mod support is planned for the next big update!

**Comment by GiovanH** [comment]
See https://github.com/Bambosh/unofficial-homestuck-collection/issues/43
