### ISSUE TITLE
New reader retcons

### ISSUE THREAD

**Issue by GiovanH** [Bambosh/unofficial-homestuck-collection#50]
Come up with a clever way of giving new readers the option to see the comic with oil retcons and such without spoiling it

**Comment by GiovanH** [comment]
![image](https://user-images.githubusercontent.com/6759280/99241856-536ca800-27f6-11eb-95ce-16f346251428.png)
One way is something like this
I like leaning hard on the "originally published"/"revised" distinction
because that doesn't spoil the textual retcon element

**Comment by Bambosh** [comment]
This is a fantastic way of framing it! I wouldn't mind being a bit more heavy handed in nudging the uninitiated to select the replay option (if only to stop them heading to their closest forum to ask themselves), but as-is, this is great.

**Comment by GiovanH** [comment]
Resolved with #135
