### ISSUE TITLE
"Hide fullscreen header" setting doesn't work when zoomed in/out

### ISSUE THREAD

**Issue by Mawile0** [Bambosh/unofficial-homestuck-collection#511]
**Describe the bug**
When you zoom in/out using the ctrl key with the setting "Hide fullscreen header" checked, the header reappears.

**To Reproduce**
1. Go to settings
2. Enable "hide fullscreen header"
3. Press F11 to go into full screen
4. Using the ctrl key and the +/- keys or the ctrl key and your scroll wheel, zoom in or out of the application.
5. The header reappears.

**Expected behavior**
When you zoom in/out in full screen with the "hide fullscreen header" setting enabled, the header should stay hidden.

**Screenshots**
![The_Unofficial_Homestuck_Collection_veLHOwZzEy](https://github.com/Bambosh/unofficial-homestuck-collection/assets/2673042/9ea635e6-a9a8-474b-a8ed-36f4406c3b9c)

**Desktop (please complete the following information):**
 - 2.0.7 AND 2.1.0-pre
 - Asset Pack V2
 - OS: Windows 10

**Additional context**
This issue occurs in the versions I listed, but I didn't test 2.0.5 cuz I didn't wanna redownload it. I also tested if any mods could have caused the issue since I have a lot of those, but it still happened even when I disabled all of my mods and refreshed the application.

**Comment by GiovanH** [comment]
well there's the problem https://github.com/Bambosh/unofficial-homestuck-collection/commits?author=recordcrash

**Comment by recordcrash** [comment]
whoops, my bad

**Comment by GiovanH** [comment]
the inner/outer difference is a weird one but I went ahead and updated the whole thing
