### ISSUE TITLE
Website does not link to newest version of app

### ISSUE THREAD

**Issue by ColonelOfCorn** [Bambosh/unofficial-homestuck-collection#519]
**Describe the bug**
The Homestuck Collection website does not give people the newest version when downloading the collection, so immediately upon install they will recieve a notification to download a newer version.

**To Reproduce**
1. Go to https://bambosh.dev/unofficial-homestuck-collection/
2. Click on Download / Scroll down to Download The App
3. See error

**Screenshots**
![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/65977971/2f1dd8a6-6c48-4d8d-8ce3-dc4b3245cf97)
![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/65977971/2b01525a-0010-41aa-bad1-2f58e07249f2)

**Desktop (please complete the following information):**
 - 2.0.7
 - Asset Pack V2
 - OS: Windows

**Comment by Sixthhokage1** [comment]
The website lists 2.0.7 as the latest release because officially it is; 2.1.0 - 2.2.1 are marked as pre-releases here on Github. The update checker should probably be updated to ignore pre-releases (or offer a choice of stable/testing channels but that's probably overkill for a project like this)

**Comment by GiovanH** [comment]
The in-app update checker actually *does* offer a choice of stable/testing channels, sort of: you'll get notifications for pre-release versions only if you have developer mode turned on.
