### ISSUE TITLE
(Web version) - Error on https://homestuck.giovanh.com/beta/8 - Flash SWF file is blocked by CORS policy

### ISSUE THREAD

**Issue by 123ldk** [Bambosh/unofficial-homestuck-collection#523]
**Describe the bug**
"Access to fetch has likely been blocked by CORS policy."
This appears to be the same issue that the Problem Sleuth intro faced. 
The flash file does not run.

**To Reproduce**
1. Go to '[https://homestuck.giovanh.com/beta/8](https://homestuck.giovanh.com/beta/8)'
2. Wait for Ruffle to load the flash animation
3. See error

**Expected behavior**
The flash should run after a brief loading sequence.

**Screenshots**
![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/84750829/2925b9ed-e32e-48ab-be67-1bfafc559979)

**Desktop (please complete the following information):**
 - Program version: [https://homestuck.giovanh.com/](https://homestuck.giovanh.com/)
 - Asset Pack: N/A
 - OS: Linux

**Additional context**
Ruffle error report:
# Error Info
Error name: Error
Error message: Failed to fetch: https://file.garden/YOVpTKX47HhECOuA/AssetPack/hs/00008/00008.swf
Error stack:
```
displayRootMovieDownloadFailedMessage@https://unpkg.com/@ruffle-rs/ruffle:2:356109
339/W/n.wbg.__wbg_displayRootMovieDownloadFailedMessage_ed4ad3ae9522c8a3@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.fd01cf836e307093f532.js:1:7014
<ruffle_web::ui::WebUiBackend as ruffle_core::backend::ui::UiBackend>::display_root_movie_download_failed_message::hd8cf05cdf02569e2@:wasm-function[10985]:0x9291fb
ruffle_core::loader::Loader::root_movie_loader::{{closure}}::hf4c5c08d10d65ba1@:wasm-function[869]:0x2ef2a9
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::h91e3fd193aca32fb@:wasm-function[1130]:0x39480c
wasm_bindgen_futures::queue::Queue::new::{{closure}}::hbb66f7af2d96f794@:wasm-function[3912]:0x6eba4d
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0219aedcaa846c26@:wasm-function[9848]:0x9070bb
closure4155 externref shim@:wasm-function[10162]:0x90c463
D@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.fd01cf836e307093f532.js:1:2985
f@https://unpkg.com/@ruffle-rs/ruffle/core.ruffle.fd01cf836e307093f532.js:1:2511

```

# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "Intel(R) HD Graphics"
Adapter Device Type: IntegratedGpu
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS)
Available features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_COMPRESSION_ETC2 | TEXTURE_COMPRESSION_ASTC | TEXTURE_COMPRESSION_ASTC_HDR | CLEAR_TEXTURE)
Current limits: Limits { max_texture_dimension_1d: 8192, max_texture_dimension_2d: 8192, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 640, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 32, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: https://file.garden/YOVpTKX47HhECOuA/AssetPack/hs/00008/00008.swf
Param movie: https://file.garden/YOVpTKX47HhECOuA/AssetPack/hs/00008/00008.swf
Param play: true
Param loop: true
Param quality: high
Param bgcolor: #fff
Param devicefont: false
Param allowScriptAccess: always
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: about:srcdoc
SWF URL: https://file.garden/YOVpTKX47HhECOuA/AssetPack/hs/00008/00008.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-07-27
Channel: nightly
Built: 2023-07-27T00:19:07.249Z
Commit: 583caa33896abc0709bcc16e3a531e4aeb053da3
Is extension: false

# Metadata

**Comment by 123ldk** [comment]
![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/84750829/a2d9d797-9710-484f-9dc6-b8b88833b48b)
This is what happens wehn to the url the Ruffle error report gave for the swf

**Comment by GiovanH** [comment]
Fixed. Files were missing.
