### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by turntechbiologist** [Bambosh/unofficial-homestuck-collection#532]
I just tried to install the app. I unzipped it and clicked on the .exe, but when I try to open it the following text is displayed (see screenshot)
<img width="419" alt="ugh" src="https://github.com/Bambosh/unofficial-homestuck-collection/assets/143289415/c9f8e7ad-10ac-40e0-b631-fa1a1d4dff6b">

The asset pack seems fine so I'm not sure what the problem is here?

Thanks for any tips.

**Comment by thecnoNSMB** [comment]
known issue, see #381
