### ISSUE TITLE
Application just straight up will not open in any form 

### ISSUE THREAD

**Issue by dnoid** [Bambosh/unofficial-homestuck-collection#543]
Describe the bug: I've seen some reports that had similar looking problems they were able to resolve but it seems like everyone else has been able to at least open the collection in some form, albeit buggy, but nothing is opening for me at all, not even an error message. I'm like the least technologically savvy person on earth so I expect that the answer is incredibly obvious sorry :(

-Downloaded asset pack and the 62-bit, 2.0.7 version of the application. After extracting everything and trying to run it, Windows gave me one of these little phreaks
![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/145934549/1a955d51-b84c-4723-a6c2-4718c9f078f2)

-I pressed 'run anyway', but got absolutely nothing. No new windows opened, nothing played. I tried looking around for potential answers, and found someone saying that that specific version of the application wouldn't run for them either, so I tried downloading an earlier build instead, the 2.0.4 version. I took the same steps - extracted everything, moved the asset pack to the folder for the main application, and tried to run it, but I got the same thing happening.

-I assumed at this point that it was Windows 11 doing one of its stupid nonsensical security measures bc this is a pretty new laptop so I went to turn everything related to Windows/Microsoft defender off briefly. I thought I had solved the problem in doing this, and when I tried to open the application again, I got this, which seemed like a better sign: 
![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/145934549/181e54cf-22aa-4f2f-a976-c45088a7e983)

...But, still, nothing opens or runs. I'm pretty stumped here, I've tried to troubleshoot what I can but I dunno what to do here. Sorry if there's any extra info you need I forgot to provide or if the answer is like insanely obvious and I'm just not getting it somehow lol. Thank you to anyone who sees this!

**Desktop (please complete the following information):**
 - Program version: The.Unofficial.Homestuck.Collection-2.0.4-win (64-bit ZIP version)
 - Asset Pack Version: Asset Pack V2
 - OS: Windows 11

**Comment by dnoid** [comment]
Resolved the issue! But I'm not entirely sure what actually got it to work for me lol. I'll describe what I did here.
-Installed 7zip at a friend's suggestion since Windows 11 kinda sucks
-Still didn't open, same friend suggested I go in Task Manager to see what happened when I tried to run the program
-Once in Task Manager, I saw like 5 separate instances of the UHC running even though it didn't appear to respond to me at all. I ended the task for all of them
-Tried opening the collection regularly again and this time it worked! 

To anyone having the same problem as me, particularly if you're also on Windows 11, try installing 7zip as opposed to winrar/whatever your computer defaults to and look into the Task Manager to see if anything's running in the background. (also I stg I checked to see if people had similar issues and couldn't find anything here but after submitting this I saw THREE different posts describing the same thing. none of them had solutions posted tho so I'm hoping this wasn't completely sloppy of me)

**Comment by thecnoNSMB** [comment]
The program won't open if it detects an instance is already running, so what probably happened is that at some point it crashed ungracefully and failed to exit, causing new instances to fail to start. I had a similar issue with Steam years ago. A reboot should always fix the problem.
