### ISSUE TITLE
pleaze tell me in exact terms how to run this

### ISSUE THREAD

**Issue by erangeals** [Bambosh/unofficial-homestuck-collection#546]
there isnt a .exe file so im stumped

**Comment by erangeals** [comment]
like i checked that i wasn't on a bad branch downloaded both main and what the website rederected me to 
got both files unzipped still dont know how to run it

**Comment by Sixthhokage1** [comment]
Click on "v2.0.7" on the sidebar where it says "Releases". Download `The-Unofficial-Homestuck-Collection-2.0.7-win-x64.zip`. Unzip it and run `The Unofficial Homestuck Collection.exe`.

**Comment by erangeals** [comment]
i will try that version and report how it goes

**Comment by erangeals** [comment]
it worked  thank you for guiding me to the correct thing to download i will use the other clearly developer-side files  as practice material if i ever want to learn vue
