### ISSUE TITLE
Correct Earth-C Snaps description

### ISSUE THREAD

**Issue by illusoryMechanist** [Bambosh/unofficial-homestuck-collection#548]
**Describe the bug**
The description for the Earth-C Snaps implies *all* snaps are decanonized, when [according to the QnA that decanonized some of them](https://www.reddit.com/r/homestuck/comments/b71z4s/comment/ejoo8qq/?utm_source=share&utm_medium=web2x&context=3) only the snaps that were not in the credits were decanonized.

**To Reproduce**
1. Go to [https://homestuck.giovanh.com/](https://homestuck.giovanh.com/)
2. Scroll down to "Snapchat"
3. See error

**Expected behavior**
The description should specify that only the snaps not included in the credits are non-canonical.

**Screenshots**
![snip tool](https://github.com/Bambosh/unofficial-homestuck-collection/assets/134031386/54669810-a2d3-4fc1-9d96-02f4feb8b1eb)
![snip tool 2](https://github.com/Bambosh/unofficial-homestuck-collection/assets/134031386/895fde09-1586-4889-9bc8-bea44e16d656)

**Desktop (please complete the following information):**
 - Program version
 - Asset Pack Version
 - OS: [Windows/Mac/Linux version X.XX]

**Additional context**

**Comment by thecnoNSMB** [comment]
I don't know if your suggested text would fit, and arguably it's a spoiler. I suggest the phrasing "Mostly are no longer canon" or "Most of these are no longer canon".

**Comment by GiovanH** [comment]
agree this is worth addressing somehow

**Comment by illusoryMechanist** [comment]
> I don't know if your suggested text would fit, and arguably it's a spoiler. I suggest the phrasing "Mostly are no longer canon" or "Most of these are no longer canon".

Maybe "Partially decanonized as of the Epilouges" would work best, with there being a button at the top of the list of the snaps to display which snaps are canon vs not by color coding them? (maybe something like green for canon, red for non-canon.)

**Comment by illusoryMechanist** [comment]
This may need to be revisited again due to Beyond Canon making explicit reference to the snaps that were de-canonized.
I would suggest replacing "No longer canon as of The Epilogues." with "Some snaps are dubiously canon as of HS:BC."
