### ISSUE TITLE
Search does not function

### ISSUE THREAD

**Issue by NadnerbD** [Bambosh/unofficial-homestuck-collection#554]
**Describe the bug**
The search function never returns any results.

**To Reproduce**
Open application
Click the "search" link at the top
Type anything into the search bar
Press enter
Wait more than a few seconds
Open dev console
See error thrown when search was attempted

**Expected behavior**
Search will return results

**Screenshots**
![The_Unofficial_Homestuck_Collection_2023-11-29_00-45-56](https://github.com/Bambosh/unofficial-homestuck-collection/assets/721347/97165053-90c2-4b8f-ac07-841b10a96b63)

**Desktop (please complete the following information):**
 - Program version: 2.4.1-win-x64
 - Asset Pack Version: Asset Pack V2
 - OS: Windows 7

**Comment by GiovanH** [comment]
Present in 2.4.1 but fixed in 2.4.2.
