### ISSUE TITLE
 Homestuck Collection says I'm not using V2 (i'm using V2)

### ISSUE THREAD

**Issue by Regale-Tress** [Bambosh/unofficial-homestuck-collection#563]
---

Homestuck Collection says I'm not using V2 (i'm using V2)

**To Reproduce**
1. Locate Asset Pack V2
2. Click on "All done, let's roll!"
3. Do first 2 steps again because it thinks i'm using not V2
4. Homestuck collection crashes and restarts at the beginning

here's a video of this sorry if i sound stupid and eepy i pulled an all nighter :(
https://drive.google.com/file/d/1cgCjEGzu8U-JqfcoOHKV-4bYH5Gj6RZg/view?usp=sharing

**Expected behavior**
For homestuck collection to not crash and restart

![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/142779611/74fcc2f4-193a-43e1-9ad1-e5ee34c7b0a9)

**Desktop (please complete the following information):**
 - 2.4.1
 -V2
 - Win11

**Comment by Neveralf** [comment]
this bug only happens to me on 2.4.1. Try downgrading to 2.2.1, it worked for me.

**Comment by GiovanH** [comment]
Can confirm. Something broke in the setup process between 2.2.1 and 2.4.1. Investigating.
