### ISSUE TITLE
one year older - "flying car" has the wrong bandcamp link 

### ISSUE THREAD

**Issue by probablyapineapple** [Bambosh/unofficial-homestuck-collection#569]
music/track/flying-car links michael guy bowman's "fly" on bandcamp when it should link erik scheele's "flying car".

**Comment by GiovanH** [comment]
This has been fixed. You are on an old version.

**Comment by probablyapineapple** [comment]
> This has been fixed. You are on an old version.

i have version 2.0.7 is that not the newest version?? im confused

**Comment by thecnoNSMB** [comment]
What Gio means to say is that the bug is fixed in the [prereleases](https://github.com/Bambosh/unofficial-homestuck-collection/releases), which you can find by clicking the "Releases" header on the side of the main Github page (*not* 2.0.7 specifically, the header above it).
