### ISSUE TITLE
Better CW for CURSED_HISTORY

### ISSUE THREAD

**Issue by GiovanH** [Bambosh/unofficial-homestuck-collection#57]
I put "holocaust" for the quick-tag, but I'm not sure about it. What's a good short CW for that document?

**Comment by Bambosh** [comment]
Holocaust proooobably covers it? Though if we're gonna fill in the gaps for the critical assets/some kinda file browser, we might need something heftier to cover the sbahj mpreg. sbahj mpreg. sbahj mpr
