### ISSUE TITLE
Pesterlog text wraparound issue, page 2176

### ISSUE THREAD

**Issue by LucidusAtra** [Bambosh/unofficial-homestuck-collection#571]
Issue:
On Homestuck page 2176, even at the smallest font size, AG's third message extends past the edge of the text box. On the official Homestuck website, the final "haaaaaaaa!" of her message is placed on the next line down. This may be an issue with the asset pack and not the viewer itself.

**To Reproduce**
1. Go to Homestuck page 2176
2. Click "Show Pesterlog"

**Expected behavior**
Ag's third message will extend past the edge of the text box at any font size.

**Screenshots**
Font size 1
![Screenshot 2024-03-09 165502](https://github.com/Bambosh/unofficial-homestuck-collection/assets/24499862/1eacab12-5144-4c43-9906-677435b6ed60)

Font size 2
![Screenshot 2024-03-09 165527](https://github.com/Bambosh/unofficial-homestuck-collection/assets/24499862/237f307e-c900-4bbb-85fd-d2457b49f584)

Font size 3 (my preferred size)
![Screenshot 2024-03-09 165545](https://github.com/Bambosh/unofficial-homestuck-collection/assets/24499862/7537cdba-aa13-43cc-a55a-053dc91eaeed)

 - Program version: V2.0.7
 - Asset Pack Version: v2
 - OS: Windows 11
 
 EDIT: Downloaded and checked the issue on the newest pre-release version, V2.4.1. Behavior is identical.

**Comment by thecnoNSMB** [comment]
Weird, I can't reproduce this. I'm running the same version number, but on the appimage in Nobara Linux.

**Comment by GiovanH** [comment]
@LucidusAtra What are your exact **Text Override** settings?
