### ISSUE TITLE
The search function does not seem to work

### ISSUE THREAD

**Issue by HarryHinderson** [Bambosh/unofficial-homestuck-collection#573]
**Describe the bug**
The search function does not work. Although the URL at the top changes, the webpage itself does not change when entering something into the search tab.

**To Reproduce**
1. Navigate to the search tab
2. Type anything into the search bar
3. Wait any length of time
4. Be met with absolutely nothing
**Expected behavior**
The search function searches functionally

**Screenshots**
![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/73373341/81dc1040-984d-44bb-b40d-613bca28922d)

**Desktop:**
 - 2.4.1
 - v2
 - OS: Windows 10

**Additional context**
I attempted a factory reset of the collection, but the issue still persisted.
I then attempted to use the latest stable release of the collection, where the search function was working previously, but this version no longer seems to work and instead gives an error message
![image](https://github.com/Bambosh/unofficial-homestuck-collection/assets/73373341/64a64a1c-c640-46fc-9a75-b3f9c4625cff)

**Comment by GiovanH** [comment]
See 2.4.2

**Comment by HarryHinderson** [comment]
wow, you're fast
