### ISSUE TITLE
New word wraparound problem in Pesterlogs after the new 2.4.2 change in the behavior when "Spacing between chat paragraphs" is checked

### ISSUE THREAD

**Issue by LucidusAtra** [Bambosh/unofficial-homestuck-collection#574]
Issue:
After issue  #571 was fixed in version 2.4.2, text does indeed wrap around in the pesterlogs while "Spacing between chat paragraphs" is checked. However, at certain font sizes (I haven't extensively checked every page, but have seen this on various pages), words are cut in half, with the other half of the cut-off word appearing on the line below.

*To Reproduce*

1. Set font size to 3
2. Open a page with a pesterlog (or even open the sample pesterlog that appears in the settings)

*Expected behavior*
Words at the end of a line of text will be cut in half, split between two lines

*Screenshots*

Note that the words "awesome" and "applejuice" in the below screenshot are split between two lines.
![Screenshot 2024-03-14 233806](https://github.com/Bambosh/unofficial-homestuck-collection/assets/24499862/24772382-6b7c-4b76-adcf-0b4a866b0f3b)

Many words are split between lines in this pesterlog example, making it somewhat difficult to read.
![Screenshot 2024-03-14 233955](https://github.com/Bambosh/unofficial-homestuck-collection/assets/24499862/70fca264-ee91-40d3-8aa3-1b171c52333b)

This issue may also occur at different font sizes. The few pages I checked at sizes 1 and 2 seemed normal, but I didn't thoroughly check every page.

Program version: V2.4.2
Asset Pack Version: v2
OS: Windows 11
Font size: 3
Line height: 2
High contrast text checked
Spacing between chat paragraphs checked.

**Comment by GiovanH** [comment]
whoops

**Comment by GiovanH** [comment]
Fixed https://github.com/Bambosh/unofficial-homestuck-collection/commit/ed4285a2eee917a150853ed6a6e1c8f9bef9ad26
