### ISSUE TITLE
[S] Terezi: Proceed and [S] Flip. both don't seem to be working

### ISSUE THREAD

**Issue by YaBoiMahkno** [Bambosh/unofficial-homestuck-collection#59]
From what I can tell, the issue stems from the "Objection!" effect that's supposed to come up when you try to interact with the flash.

No matter what I try to do the flash doesn't detect my interactions with it, so the "Objection!" effect never comes up. The only thing that can be interacted with is the volume icon on the top right. In both flashes, Terezi is simply stuck on her animation loop with no way to proceed.

I am on a PC btw, in case this issue is unique to this version of the program.

**Comment by GiovanH** [comment]
Can't reproduce on v1.1. Is the flash in focus? (Did you click on it first?)

**Comment by GiovanH** [comment]
Other troubleshooting questions:

- What version of windows are you on? (xp, 7, 10?)
- Do you have JS enhanced flashes enabled?
- Does the flash work in your browser? (http://mspaintadventures.com/newindex.php?s=6&p=005660)

**Comment by YaBoiMahkno** [comment]
- The flash is in focus, I clicked on it first
- I'm on windows 10
- I don't have JS enhanced flashes enabled
- Ah well I think I've found the problem, it doesn't work on my browser either.

Hmm, well I guess the problem's on my end then, weird that only those two flashes don't work.

Well anyway, thanks for the help!

**Comment by GiovanH** [comment]
Even if this isn't a bug with UHC I'm curious at this point. 

What specifically does it look like? For Flip, does terezi animate with the animated red arrow underneath? Does anything happen when you press the down arrow key (animation stops, etc)?

**Comment by YaBoiMahkno** [comment]
Welp today I learned I'm an absolute dumbass who somehow forgot how these two flashes worked on his third read through. 

Thanks for helping me out tho, and sorry for taking your time.

**Comment by GiovanH** [comment]
oop. Well, mystery solved, anyway.
