### ISSUE TITLE
/unlock is grouped under Problem Sleuth despite Tavros

### ISSUE THREAD

**Issue by GiovanH** [Bambosh/unofficial-homestuck-collection#60]
definitely weird organization, possibly a spoiler issue?

**Comment by Niklink** [comment]
Well, nearly all of them were PS-related. The last two donation pages with Homestuck spoilers are actually spoiler-gated in New Reader Mode.

**Comment by GiovanH** [comment]
Good to know they're properly spoiled at any rate
