### ISSUE TITLE
Command text appears cut off in "[S] YOU THERE. BOY."

### ISSUE THREAD

**Issue by dekarrin** [Bambosh/unofficial-homestuck-collection#68]
While running on Windows 10, it looks like some of the command text that pops up when an interactable item is clicked is cut off; i.e. "> THIS LARGE PLATFORM. GOOD GRIEF, WHAT IS IT BOY?" has the text cut off in the middle of the last O.

It doesn't look like it stops one from understanding what is mentioned there, but the presentation suffers for it.

Since this is in a flash, not sure if the issue is latent to the flash file itself, or if it was originally present and thus is preserved by design here.

Is this something that is by design? If not, is this something that a fix could be applied to?

**Comment by GiovanH** [comment]
Correct behavior is for the popup to position itself somewhere onscreen when you click it, but once you've done that you can walk away, and it will appear cut-off. I think this is probably what you're describing? Let me know if it isn't.
![image](https://user-images.githubusercontent.com/6759280/111924936-cc199480-8a74-11eb-8939-e5cfec5ebe21.png)
