### ISSUE TITLE
Add-on idea: Annotation/Citations

### ISSUE THREAD

**Issue by creatrixtiara** [Bambosh/unofficial-homestuck-collection#7]
Hi!

Firstly, this looks super impressive already and I'm looking forward to diving into the entire project.

I was wondering if there would be interest in using this as a base for an Annotated Homestuck - kind of like Genius but for Homestuck instead of song lyrics. The whole thing is so full of references and it'd be cool to have an add-on that would highlight certain words or give footnotes like "Con-Air is a movie that was released in 19XX and starred Nicolas Cage etc etc" or "Terezi's theme here is based on the Ace Attorney soundtrack" or even self-referential things like "this is a callback to this SBAHJ comic". You kind of have that with the Fandom Wikia but having it within the text as you read through Homestuck would really enhance the experience.

One thing that could be tricky to code is a way to regularly update annotations as they come in. Have an online system where people can crowdsource annotations ala Genius, then link that to an add-on attached to this app so that they sync up.

I'm not super strong at coding so I wouldn't even know where to begin with coding this, but I could definitely help with the content and citations if this takes off!

**Comment by Bambosh** [comment]
Footnote support is planned for a future update, when I get the ball rolling on a proper mod loader.

**Comment by GiovanH** [comment]
Footnotes support is an explicit goal on #28.
