### ISSUE TITLE
Problem Sleuth Title Screen Youtube link redirects to a video which is unavailable.

### ISSUE THREAD

**Issue by lKomus** [Bambosh/unofficial-homestuck-collection#70]
Hello.

The original video got deleted so the link in the Music section must be changed. Thankfully someone else reuploaded it there: https://www.youtube.com/watch?v=OtFH_VaHFwY but maybe there's a better link on another website.

**Comment by GiovanH** [comment]
Added to the patch, will be fixed in the next asset release
