### ISSUE TITLE
Full Screen as Full Screen

### ISSUE THREAD

**Issue by CaviaPorcellus** [Bambosh/unofficial-homestuck-collection#81]
When you enter Full Screen mode, the title and tab bars are still shown.

I assume this isn't a bug, but intentional. But it would be nice for full screen to act like it does in a browser.

Thank you for your work regardless!

(This is using the Linux version at least, on Ubuntu 16.04.)

**Comment by Bambosh** [comment]
Wouldn't be against having something like this as a feature!
