### ISSUE TITLE
Find dialog finds itself

### ISSUE THREAD

**Issue by CaviaPorcellus** [Bambosh/unofficial-homestuck-collection#82]
When searching for text using the find function (ctrl-f), in addition to finding text on the displayed page, the dialog also finds and counts words in the dialog box itself (e.g., it finds the word "match" once when it only appears in the dialog).

![Screenshot from 2021-01-29 01-38-38](https://user-images.githubusercontent.com/5825551/106322067-44b55f00-6243-11eb-9198-8f25939fc01c.png)

Thanks.

**Comment by GiovanH** [comment]
this is hilarious
