### ISSUE TITLE
Default flash quality is medium, not high

### ISSUE THREAD

**Issue by CaviaPorcellus** [Bambosh/unofficial-homestuck-collection#84]
All the flash pages are set to display in medium quality (right-click on a flash animation or game, then click Quality). It would be nice if the default was always set to High.

The difference between them isn't always the largest, but since all the files are local there's no reason to go with the nicest version (that I can think of anyhow). Users can currently select high quality, but the changes aren't saved, even when going back to the same page. If there's a reason not to use high by default, allowing the user set changes to persist would be nice (ideally across all flash pages), though I have no clue how difficult that is to implement. Thanks!

**Comment by GiovanH** [comment]
This appears to be a bug; `MediaEmbed` already tries to set the quality to high via params here https://github.com/Bambosh/unofficial-homestuck-collection/blob/7db80b0d1ac9ca8e5537931ed43fd83226b069c3/src/components/UIElements/MediaEmbed.vue#L263

I can definitely reproduce it here, though, so possibly an issue passing params through multiple frames?

**Comment by GiovanH** [comment]
I believe this was fixed with https://github.com/Bambosh/unofficial-homestuck-collection/pull/86? My flash quality is now consistently set to High, anyway, and it wasn't before.
