### ISSUE TITLE
Saved scroll position on horizontal images

### ISSUE THREAD

**Issue by Pyrocasher** [Bambosh/unofficial-homestuck-collection#9]
I ran into a small issue at the start of A6A6I4. The horizontal images located on pages 6948, 6950, and 6957 all seem to share the same scroll position. For example, when I found this issue, I scrolled all the way to the right on 6948, and when I reached 6950, the image was already scrolled to the right. I don't remember if there are any other parts of the comic with horizontal scrolling like this, but if there is, they might also be affected.

![johnislost](https://user-images.githubusercontent.com/23088226/97495104-a5c85080-193d-11eb-808d-452f3170e5c6.gif)

**Comment by Bambosh** [comment]
Got a fix for this coming in the next release!
